package xyz.junerver.compose.palette.core.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
data class PaletteComponentThemes(
    val borderContainer: PaletteBorderContainerTokens,
    val button: PaletteButtonTokens,
    val checkbox: PaletteCheckboxTokens,
    val radio: PaletteRadioTokens,
    val switch: PaletteSwitchTokens,
    val selectionControl: PaletteSelectionControlTokens,
    val form: PaletteFormTokens,
    val textField: PaletteTextFieldTokens,
    val select: PaletteSelectTokens,
    val dateTime: PaletteDateTimeTokens,
    val input: PaletteInputTokens,
    val card: PaletteCardTokens,
    val table: PaletteTableTokens,
    val dataGrid: PaletteDataGridTokens,
    val dataDisplay: PaletteDataDisplayTokens,
    val dataEntry: PaletteDataEntryTokens,
    val navigationMenu: PaletteNavigationMenuTokens,
    val appBar: PaletteAppBarTokens,
    val floatingLayer: PaletteFloatingLayerTokens,
    val dialog: PaletteDialogTokens,
    val drawer: PaletteDrawerTokens,
    val popup: PalettePopupTokens,
    val actionSheet: PaletteActionSheetTokens,
    val message: PaletteMessageTokens,
    val notification: PaletteNotificationTokens,
    val toast: PaletteToastTokens,
    val tag: PaletteTagTokens,
    val feedbackDisplay: PaletteFeedbackDisplayTokens,
    val progress: PaletteProgressTokens,
    val media: PaletteMediaTokens,
    val utility: PaletteUtilityTokens,
    val layout: PaletteLayoutTokens,
    val floatingAction: PaletteFloatingActionTokens,
    val screen: PaletteScreenTokens,
) {
    companion object {
        fun default(
            colors: PaletteColors = PaletteColors(),
            spacing: PaletteSpacing = PaletteSpacing(),
            typography: PaletteTypography = PaletteTypography(),
            opacity: PaletteOpacity = PaletteOpacity(),
            motion: PaletteMotion = PaletteMotion(),
            elevation: PaletteElevation = PaletteElevation(),
            control: PaletteControlTokens = PaletteControlTokens(),
            darkTheme: Boolean = false,
        ): PaletteComponentThemes = PaletteComponentThemes(
            borderContainer = PaletteBorderContainerTokens.default(colors, spacing, control),
            button = PaletteButtonTokens.default(colors, spacing, typography, opacity, darkTheme),
            checkbox = PaletteCheckboxTokens.default(colors, opacity, motion),
            radio = PaletteRadioTokens.default(colors, spacing, typography, opacity, motion),
            switch = PaletteSwitchTokens.default(colors, opacity, motion),
            selectionControl = PaletteSelectionControlTokens.default(colors, spacing, typography, opacity, motion, elevation),
            form = PaletteFormTokens.default(colors, spacing, typography),
            textField = PaletteTextFieldTokens.default(colors, typography, opacity, motion, elevation, control),
            select = PaletteSelectTokens.default(colors, spacing, typography, opacity, control),
            dateTime = PaletteDateTimeTokens.default(colors, spacing, typography, control),
            input = PaletteInputTokens.default(colors, spacing, typography, opacity, motion, control),
            card = PaletteCardTokens.default(colors, spacing, elevation),
            table = PaletteTableTokens.default(colors, spacing, typography),
            dataGrid = PaletteDataGridTokens.default(colors, spacing, typography),
            dataDisplay = PaletteDataDisplayTokens.default(colors, spacing, typography),
            dataEntry = PaletteDataEntryTokens.default(colors, spacing, typography, opacity, control),
            navigationMenu = PaletteNavigationMenuTokens.default(colors, spacing, typography, opacity, motion, elevation),
            appBar = PaletteAppBarTokens.default(colors, spacing, typography),
            floatingLayer = PaletteFloatingLayerTokens.default(colors, spacing, typography, opacity, elevation, darkTheme),
            dialog = PaletteDialogTokens.default(colors, spacing, typography),
            drawer = PaletteDrawerTokens.default(colors, spacing, opacity, elevation, motion),
            popup = PalettePopupTokens.default(colors, spacing, typography, motion),
            actionSheet = PaletteActionSheetTokens.default(colors, spacing, typography, opacity),
            message = PaletteMessageTokens.default(colors, spacing, typography, opacity, motion),
            notification = PaletteNotificationTokens.default(colors, spacing, typography, opacity, motion, darkTheme),
            toast = PaletteToastTokens.default(colors, spacing, typography, motion, darkTheme),
            tag = PaletteTagTokens.default(colors, spacing, opacity),
            feedbackDisplay = PaletteFeedbackDisplayTokens.default(colors, spacing, typography, opacity),
            progress = PaletteProgressTokens.default(colors, spacing, typography, opacity, motion, darkTheme),
            media = PaletteMediaTokens.default(colors, spacing, typography, opacity, control),
            utility = PaletteUtilityTokens.default(colors, spacing, typography, opacity, control),
            layout = PaletteLayoutTokens.default(spacing),
            floatingAction = PaletteFloatingActionTokens.default(colors, spacing, typography, elevation, motion),
            screen = PaletteScreenTokens.default(colors),
        )
    }
}

@Immutable
data class PaletteBorderContainerTokens(
    val height: Dp,
    val width: Dp,
    val borderWidth: Dp,
    val cornerRadius: Dp,
    val contentPadding: Dp,
    val borderColor: Color,
    val backgroundColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            control: PaletteControlTokens,
        ): PaletteBorderContainerTokens = PaletteBorderContainerTokens(
            height = 28.dp,
            width = 300.dp,
            borderWidth = control.borderWidth,
            cornerRadius = control.medium.cornerRadius,
            contentPadding = spacing.small,
            borderColor = colors.border,
            backgroundColor = colors.surface,
        )
    }
}

@Immutable
data class PaletteCheckboxSizeTokens(
    val size: Dp,
    val touchPadding: Dp,
    val strokeWidth: Dp,
    val cornerRadius: Dp,
    val focusRingOffset: Dp,
)

@Immutable
data class PaletteCheckboxTokens(
    val checkedColor: Color,
    val uncheckedColor: Color,
    val checkmarkColor: Color,
    val disabledColor: Color,
    val focusColor: Color,
    val hoverColor: Color,
    val disabledBorderAlpha: Float,
    val focusRingAlpha: Float,
    val hoverBackgroundAlpha: Float,
    val motionDuration: Int,
    val small: PaletteCheckboxSizeTokens,
    val medium: PaletteCheckboxSizeTokens,
    val large: PaletteCheckboxSizeTokens,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
        ): PaletteCheckboxTokens = PaletteCheckboxTokens(
            checkedColor = colors.primary,
            uncheckedColor = colors.border,
            checkmarkColor = colors.onPrimary,
            disabledColor = colors.borderDisabled,
            focusColor = colors.borderFocus,
            hoverColor = colors.borderHover,
            disabledBorderAlpha = opacity.disabled,
            focusRingAlpha = 0.3f,
            hoverBackgroundAlpha = opacity.hover,
            motionDuration = motion.durationNormal,
            small = PaletteCheckboxSizeTokens(
                size = 14.dp,
                touchPadding = 8.dp,
                strokeWidth = 2.dp,
                cornerRadius = 2.dp,
                focusRingOffset = 2.dp,
            ),
            medium = PaletteCheckboxSizeTokens(
                size = 16.dp,
                touchPadding = 8.dp,
                strokeWidth = 2.dp,
                cornerRadius = 2.dp,
                focusRingOffset = 2.dp,
            ),
            large = PaletteCheckboxSizeTokens(
                size = 20.dp,
                touchPadding = 8.dp,
                strokeWidth = 2.dp,
                cornerRadius = 2.dp,
                focusRingOffset = 2.dp,
            ),
        )
    }
}

@Immutable
data class PaletteRadioSizeTokens(
    val outerSize: Dp,
    val innerSize: Dp,
    val touchPadding: Dp,
    val strokeWidth: Dp,
    val focusRingOffset: Dp,
)

@Immutable
data class PaletteRadioTokens(
    val labelColor: Color,
    val descriptionColor: Color,
    val checkedColor: Color,
    val uncheckedColor: Color,
    val disabledColor: Color,
    val focusColor: Color,
    val hoverColor: Color,
    val itemPadding: Dp,
    val itemRadius: Dp,
    val descriptionSpacing: Dp,
    val labelTextStyle: TextStyle,
    val descriptionTextStyle: TextStyle,
    val disabledAlpha: Float,
    val focusRingAlpha: Float,
    val hoverBackgroundAlpha: Float,
    val motionDuration: Int,
    val small: PaletteRadioSizeTokens,
    val medium: PaletteRadioSizeTokens,
    val large: PaletteRadioSizeTokens,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
        ): PaletteRadioTokens = PaletteRadioTokens(
            labelColor = colors.textPrimary,
            descriptionColor = colors.textTertiary,
            checkedColor = colors.primary,
            uncheckedColor = colors.border,
            disabledColor = colors.borderDisabled,
            focusColor = colors.borderFocus,
            hoverColor = colors.borderHover,
            itemPadding = spacing.medium,
            itemRadius = 10.dp,
            descriptionSpacing = spacing.extraSmall,
            labelTextStyle = typography.body.copy(fontSize = 17.sp),
            descriptionTextStyle = typography.body.copy(fontSize = typography.body.fontSize),
            disabledAlpha = opacity.muted,
            focusRingAlpha = 0.3f,
            hoverBackgroundAlpha = opacity.hover,
            motionDuration = motion.durationNormal,
            small = PaletteRadioSizeTokens(
                outerSize = 14.dp,
                innerSize = 6.dp,
                touchPadding = 8.dp,
                strokeWidth = 2.dp,
                focusRingOffset = 2.dp,
            ),
            medium = PaletteRadioSizeTokens(
                outerSize = 16.dp,
                innerSize = 8.dp,
                touchPadding = 8.dp,
                strokeWidth = 2.dp,
                focusRingOffset = 2.dp,
            ),
            large = PaletteRadioSizeTokens(
                outerSize = 20.dp,
                innerSize = 10.dp,
                touchPadding = 8.dp,
                strokeWidth = 2.dp,
                focusRingOffset = 2.dp,
            ),
        )
    }
}

@Immutable
data class PaletteSwitchTokens(
    val checkedTrackColor: Color,
    val uncheckedTrackColor: Color,
    val thumbColor: Color,
    val disabledTrackColor: Color,
    val width: Dp,
    val height: Dp,
    val thumbSize: Dp,
    val thumbOffset: Dp,
    val checkedThumbOffset: Dp,
    val borderRadius: Dp,
    val thumbBorderRadius: Dp,
    val disabledAlpha: Float,
    val motionDuration: Int,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
        ): PaletteSwitchTokens = PaletteSwitchTokens(
            checkedTrackColor = colors.primary,
            uncheckedTrackColor = colors.border,
            thumbColor = colors.surface,
            disabledTrackColor = colors.borderDisabled,
            width = 50.dp,
            height = 26.dp,
            thumbSize = 22.dp,
            thumbOffset = 2.dp,
            checkedThumbOffset = 26.dp,
            borderRadius = 16.dp,
            thumbBorderRadius = 50.dp,
            disabledAlpha = opacity.disabled,
            motionDuration = motion.durationNormal,
        )
    }
}

@Immutable
data class PaletteSelectionControlTokens(
    val sliderActiveTrackColor: Color,
    val sliderInactiveTrackColor: Color,
    val sliderThumbColor: Color,
    val sliderLabelColor: Color,
    val sliderThumbShadowColor: Color,
    val sliderDisabledTrackColor: Color,
    val sliderHeight: Dp,
    val sliderTrackHeight: Dp,
    val sliderThumbSize: Dp,
    val sliderThumbShadowElevation: Dp,
    val sliderLabelSpacing: Dp,
    val sliderLabelWidth: Dp,
    val sliderLabelTextStyle: TextStyle,
    val sliderDisabledAlpha: Float,
    val rateActiveColor: Color,
    val rateInactiveColor: Color,
    val rateDisabledColor: Color,
    val rateSmallStarSize: Dp,
    val rateMediumStarSize: Dp,
    val rateLargeStarSize: Dp,
    val togglePressedContainerColor: Color,
    val toggleDefaultContainerColor: Color,
    val togglePressedBorderColor: Color,
    val toggleDefaultBorderColor: Color,
    val togglePressedContentColor: Color,
    val toggleDefaultContentColor: Color,
    val toggleCornerRadius: Dp,
    val togglePaddingHorizontal: Dp,
    val togglePaddingVertical: Dp,
    val toggleGroupSpacing: Dp,
    val toggleBorderWidth: Dp,
    val toggleItemIconSpacing: Dp,
    val toggleDisabledAlpha: Float,
    val toggleGroupContainerColor: Color,
    val toggleGroupContainerCornerRadius: Dp,
    val toggleGroupContainerPaddingHorizontal: Dp,
    val toggleGroupContainerPaddingVertical: Dp,
    val segmentedContainerColor: Color,
    val segmentedSelectedItemColor: Color,
    val segmentedTextColor: Color,
    val segmentedSelectedTextColor: Color,
    val segmentedDisabledTextColor: Color,
    val segmentedCornerRadius: Dp,
    val segmentedItemPaddingHorizontal: Dp,
    val segmentedItemPaddingVertical: Dp,
    val segmentedItemIconSpacing: Dp,
    val segmentedIndicatorAnimationDurationMillis: Int,
    val segmentedDisabledAlpha: Float,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
            elevation: PaletteElevation,
        ): PaletteSelectionControlTokens = PaletteSelectionControlTokens(
            sliderActiveTrackColor = colors.primary,
            sliderInactiveTrackColor = colors.border,
            sliderThumbColor = colors.primary,
            sliderLabelColor = colors.textPrimary,
            sliderThumbShadowColor = colors.shadow,
            sliderDisabledTrackColor = colors.borderDisabled,
            sliderHeight = 48.dp,
            sliderTrackHeight = 2.dp,
            sliderThumbSize = 28.dp,
            sliderThumbShadowElevation = elevation.focusShadowBlur,
            sliderLabelSpacing = spacing.small + spacing.extraSmall,
            sliderLabelWidth = 40.dp,
            sliderLabelTextStyle = typography.body.copy(fontSize = 14.sp),
            sliderDisabledAlpha = opacity.disabled,
            rateActiveColor = colors.warning,
            rateInactiveColor = colors.border,
            rateDisabledColor = colors.borderDisabled,
            rateSmallStarSize = 20.dp,
            rateMediumStarSize = 26.dp,
            rateLargeStarSize = 32.dp,
            togglePressedContainerColor = colors.primary.copy(alpha = (opacity.selected + opacity.hover) / 2f),
            toggleDefaultContainerColor = Color.Transparent,
            togglePressedBorderColor = colors.primary,
            toggleDefaultBorderColor = colors.border,
            togglePressedContentColor = colors.primary,
            toggleDefaultContentColor = colors.textPrimary,
            toggleCornerRadius = 6.dp,
            togglePaddingHorizontal = spacing.small + spacing.extraSmall,
            togglePaddingVertical = spacing.small,
            toggleGroupSpacing = spacing.none,
            toggleBorderWidth = 1.dp,
            toggleItemIconSpacing = spacing.extraSmall,
            toggleDisabledAlpha = opacity.disabled,
            toggleGroupContainerColor = colors.border,
            toggleGroupContainerCornerRadius = 8.dp,
            toggleGroupContainerPaddingHorizontal = spacing.extraSmall,
            toggleGroupContainerPaddingVertical = spacing.extraSmall,
            segmentedContainerColor = colors.border,
            segmentedSelectedItemColor = colors.surface,
            segmentedTextColor = colors.textPrimary,
            segmentedSelectedTextColor = colors.textPrimary,
            segmentedDisabledTextColor = colors.textDisabled,
            segmentedCornerRadius = 8.dp,
            segmentedItemPaddingHorizontal = spacing.small + spacing.extraSmall,
            segmentedItemPaddingVertical = 6.dp,
            segmentedItemIconSpacing = spacing.extraSmall,
            segmentedIndicatorAnimationDurationMillis = motion.durationNormal,
            segmentedDisabledAlpha = opacity.disabled,
        )
    }
}

@Immutable
data class PaletteButtonSizeTokens(
    val verticalPadding: Dp,
    val horizontalPadding: Dp,
    val fontSize: TextUnit,
    val borderRadius: Dp,
)

@Immutable
data class PaletteButtonTokens(
    val primaryContainerColor: Color,
    val primaryContentColor: Color,
    val dangerContainerColor: Color,
    val dangerContentColor: Color,
    val plainContainerColor: Color,
    val plainContentColor: Color,
    val outlinedContainerColor: Color,
    val outlinedContentColor: Color,
    val outlinedBorderColor: Color,
    val defaultWidth: Dp,
    val loadingSpacing: Dp,
    val disabledAlpha: Float,
    val large: PaletteButtonSizeTokens,
    val medium: PaletteButtonSizeTokens,
    val small: PaletteButtonSizeTokens,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            darkTheme: Boolean,
        ): PaletteButtonTokens = PaletteButtonTokens(
            primaryContainerColor = colors.primary,
            primaryContentColor = colors.onPrimary,
            dangerContainerColor = if (darkTheme) colors.error else colors.bgHover,
            dangerContentColor = if (darkTheme) colors.onError else colors.error,
            plainContainerColor = if (darkTheme) colors.surface else colors.bgHover,
            plainContentColor = colors.onSurface,
            outlinedContainerColor = Color.Transparent,
            outlinedContentColor = colors.primary,
            outlinedBorderColor = colors.primary,
            defaultWidth = 184.dp,
            loadingSpacing = spacing.small,
            disabledAlpha = opacity.disabledStrong,
            large = PaletteButtonSizeTokens(
                verticalPadding = 12.dp,
                horizontalPadding = spacing.large,
                fontSize = 17.sp,
                borderRadius = 8.dp,
            ),
            medium = PaletteButtonSizeTokens(
                verticalPadding = 10.dp,
                horizontalPadding = spacing.large,
                fontSize = typography.body.fontSize,
                borderRadius = 8.dp,
            ),
            small = PaletteButtonSizeTokens(
                verticalPadding = 6.dp,
                horizontalPadding = spacing.small + spacing.extraSmall,
                fontSize = typography.body.fontSize,
                borderRadius = 6.dp,
            ),
        )
    }
}

@Immutable
data class PaletteFormTokens(
    val itemSpacing: Dp,
    val labelWidth: Dp,
    val labelInputSpacing: Dp,
    val inputHelperSpacing: Dp,
    val labelTopPadding: Dp,
    val labelTextStyle: TextStyle,
    val helperTextStyle: TextStyle,
    val labelColor: Color,
    val requiredColor: Color,
    val errorColor: Color,
    val helpColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
        ): PaletteFormTokens = PaletteFormTokens(
            itemSpacing = spacing.large,
            labelWidth = 100.dp,
            labelInputSpacing = spacing.small,
            inputHelperSpacing = spacing.extraSmall,
            labelTopPadding = 6.dp,
            labelTextStyle = typography.body.copy(fontSize = 14.sp),
            helperTextStyle = typography.label,
            labelColor = colors.textSecondary,
            requiredColor = colors.error,
            errorColor = colors.error,
            helpColor = colors.textTertiary,
        )
    }
}

@Immutable
data class PaletteTextFieldTokens(
    val textColor: Color,
    val placeholderColor: Color,
    val disabledTextColor: Color,
    val prefixSuffixColor: Color,
    val countColor: Color,
    val cursorColor: Color,
    val backgroundColor: Color,
    val disabledBackgroundColor: Color,
    val borderColor: Color,
    val hoverBorderColor: Color,
    val focusBorderColor: Color,
    val disabledBorderColor: Color,
    val successBorderColor: Color,
    val warningBorderColor: Color,
    val errorBorderColor: Color,
    val focusShadowColor: Color,
    val successShadowColor: Color,
    val warningShadowColor: Color,
    val errorShadowColor: Color,
    val borderWidth: Dp,
    val focusBorderWidth: Dp,
    val cornerRadius: Dp,
    val fontSize: TextUnit,
    val shadowElevation: Dp,
    val motionDuration: Int,
    val small: PaletteControlSizeTokens,
    val medium: PaletteControlSizeTokens,
    val large: PaletteControlSizeTokens,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
            elevation: PaletteElevation,
            control: PaletteControlTokens,
        ): PaletteTextFieldTokens = PaletteTextFieldTokens(
            textColor = colors.textPrimary,
            placeholderColor = colors.hint,
            disabledTextColor = colors.textDisabled,
            prefixSuffixColor = colors.textSecondary,
            countColor = colors.textTertiary,
            cursorColor = colors.primary,
            backgroundColor = colors.surface,
            disabledBackgroundColor = colors.bgDisabled,
            borderColor = colors.border,
            hoverBorderColor = colors.borderHover,
            focusBorderColor = colors.borderFocus,
            disabledBorderColor = colors.borderDisabled,
            successBorderColor = colors.success,
            warningBorderColor = colors.warning,
            errorBorderColor = colors.error,
            focusShadowColor = colors.focusShadow,
            successShadowColor = colors.success.copy(alpha = opacity.focusRing),
            warningShadowColor = colors.warning.copy(alpha = opacity.focusRing),
            errorShadowColor = colors.errorShadow,
            borderWidth = control.borderWidth,
            focusBorderWidth = control.focusBorderWidth,
            cornerRadius = control.medium.cornerRadius,
            fontSize = typography.body.fontSize,
            shadowElevation = elevation.focusShadowBlur,
            motionDuration = motion.durationNormal,
            small = control.small,
            medium = control.medium,
            large = control.large,
        )
    }
}

@Immutable
data class PaletteSelectTokens(
    val textColor: Color,
    val placeholderColor: Color,
    val disabledTextColor: Color,
    val containerColor: Color,
    val dropdownContainerColor: Color,
    val optionTextColor: Color,
    val selectedOptionTextColor: Color,
    val selectedOptionContainerColor: Color,
    val hoverOptionContainerColor: Color,
    val disabledOptionTextColor: Color,
    val borderColor: Color,
    val disabledBorderColor: Color,
    val dividerColor: Color,
    val iconColor: Color,
    val borderWidth: Dp,
    val dropdownMinWidth: Dp,
    val dropdownMaxHeight: Dp,
    val cascaderColumnWidth: Dp,
    val cascaderColumnMaxHeight: Dp,
    val cascaderPanelColumnHeight: Dp,
    val searchFieldPadding: Dp,
    val optionHeight: Dp,
    val optionPaddingHorizontal: Dp,
    val optionCornerRadius: Dp,
    val optionTextStyle: TextStyle,
    val arrowSize: Dp,
    val treeIndent: Dp,
    val trailingIconAlpha: Float,
    val mentionTagColor: Color,
    val mentionHighlightColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            control: PaletteControlTokens,
        ): PaletteSelectTokens = PaletteSelectTokens(
            textColor = colors.textPrimary,
            placeholderColor = colors.hint,
            disabledTextColor = colors.textDisabled,
            containerColor = colors.surface,
            dropdownContainerColor = colors.surfaceElevated,
            optionTextColor = colors.textPrimary,
            selectedOptionTextColor = colors.primary,
            selectedOptionContainerColor = colors.bgSelected,
            hoverOptionContainerColor = colors.bgHover,
            disabledOptionTextColor = colors.textDisabled,
            borderColor = colors.border,
            disabledBorderColor = colors.borderDisabled,
            dividerColor = colors.divider,
            iconColor = colors.textTertiary,
            borderWidth = control.borderWidth,
            dropdownMinWidth = 240.dp,
            dropdownMaxHeight = 280.dp,
            cascaderColumnWidth = 200.dp,
            cascaderColumnMaxHeight = 220.dp,
            cascaderPanelColumnHeight = 220.dp,
            searchFieldPadding = spacing.small,
            optionHeight = 36.dp,
            optionPaddingHorizontal = spacing.small + spacing.extraSmall,
            optionCornerRadius = control.medium.cornerRadius,
            optionTextStyle = typography.body.copy(fontSize = 14.sp),
            arrowSize = 16.dp,
            treeIndent = 20.dp,
            trailingIconAlpha = opacity.disabledStrong,
            mentionTagColor = colors.primary.copy(alpha = (opacity.selected + opacity.hover) / 2f),
            mentionHighlightColor = colors.primary.copy(alpha = opacity.selected + opacity.hover / 2f),
        )
    }
}

@Immutable
data class PaletteDateTimeTokens(
    val inputPlaceholderColor: Color,
    val inputTextColor: Color,
    val inputInvalidColor: Color,
    val inputIconColor: Color,
    val inputIconSpacing: Dp,
    val calendarContainerColor: Color,
    val calendarHeaderColor: Color,
    val calendarDayOfWeekColor: Color,
    val calendarDayColor: Color,
    val calendarSelectedColor: Color,
    val calendarSelectedTextColor: Color,
    val calendarDisabledColor: Color,
    val calendarTodayBorderColor: Color,
    val calendarCellSize: Dp,
    val calendarHeaderHeight: Dp,
    val calendarDayOfWeekHeight: Dp,
    val calendarSelectedCircleSize: Dp,
    val calendarCornerRadius: Dp,
    val calendarTodayBorderWidth: Dp,
    val calendarDayTextStyle: TextStyle,
    val calendarHeaderTextStyle: TextStyle,
    val calendarDayOfWeekTextStyle: TextStyle,
    // 区间选择专用：band（起止之间的中间带）、hover 预览、pill-cap（起止端帽）、时间滚轮文字
    val calendarRangeBandColor: Color,
    val calendarRangeHoverColor: Color,
    val calendarRangeStartCapColor: Color,
    val calendarRangeEndCapColor: Color,
    val calendarRangeCapTextColor: Color,
    val timeWheelTextColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            control: PaletteControlTokens,
        ): PaletteDateTimeTokens = PaletteDateTimeTokens(
            inputPlaceholderColor = colors.hint,
            inputTextColor = colors.textPrimary,
            inputInvalidColor = colors.error,
            inputIconColor = colors.hint,
            inputIconSpacing = spacing.small,
            calendarContainerColor = colors.surface,
            calendarHeaderColor = colors.textPrimary,
            calendarDayOfWeekColor = colors.hint,
            calendarDayColor = colors.textPrimary,
            calendarSelectedColor = colors.primary,
            calendarSelectedTextColor = colors.surface,
            calendarDisabledColor = colors.hint,
            calendarTodayBorderColor = colors.primary,
            calendarCellSize = 40.dp,
            calendarHeaderHeight = 48.dp,
            calendarDayOfWeekHeight = 32.dp,
            calendarSelectedCircleSize = 32.dp,
            calendarCornerRadius = control.medium.cornerRadius + 2.dp,
            calendarTodayBorderWidth = control.borderWidth,
            calendarDayTextStyle = typography.body.copy(fontSize = 14.sp),
            calendarHeaderTextStyle = typography.body.copy(fontSize = 16.sp, fontWeight = FontWeight.Medium),
            calendarDayOfWeekTextStyle = typography.label.copy(fontSize = 12.sp),
            // 区间选择默认色板：band/hover 由 primary 派生低透明度；cap 复用 primary；cap 文字反白
            calendarRangeBandColor = colors.primary.copy(alpha = 0.14f),
            calendarRangeHoverColor = colors.primary.copy(alpha = 0.08f),
            calendarRangeStartCapColor = colors.primary,
            calendarRangeEndCapColor = colors.primary,
            calendarRangeCapTextColor = colors.surface,
            timeWheelTextColor = colors.textPrimary,
        )
    }
}

@Immutable
data class PaletteInputTokens(
    val inputNumberWidth: Dp,
    val inputNumberButtonWidth: Dp,
    val inputNumberMinButtonWidth: Dp,
    val inputNumberAnimationDurationMillis: Int,
    val inputNumberDisabledAlpha: Float,
    val inputNumberButtonColor: Color,
    val inputNumberButtonIconColor: Color,
    val inputNumberDisabledButtonColor: Color,
    val inputNumberDisabledButtonIconColor: Color,
    val inputNumberHoverButtonColor: Color,
    val inputNumberContainerColor: Color,
    val inputNumberTextColor: Color,
    val inputNumberDisabledTextColor: Color,
    val inputNumberPlaceholderColor: Color,
    val inputNumberCursorColor: Color,
    val inputNumberBorderWidth: Dp,
    val inputNumberDividerWidth: Dp,
    val inputNumberTextStyle: TextStyle,
    val otpCellWidth: Dp,
    val otpCellHeight: Dp,
    val otpCellCornerRadius: Dp,
    val otpCellSpacing: Dp,
    val otpCellBorderWidth: Dp,
    val otpTextStyle: TextStyle,
    val otpCursorWidth: Dp,
    val otpCursorHeight: Dp,
    val otpCursorBlinkDurationMillis: Int,
    val otpSeparatorWidth: Dp,
    val otpDisabledAlpha: Float,
    val otpAnimationDurationMillis: Int,
    val otpFocusedBorderColor: Color,
    val otpBorderColor: Color,
    val otpCellBackgroundColor: Color,
    val otpTextColor: Color,
    val otpCursorColor: Color,
    val otpSeparatorColor: Color,
    val searchBarHeight: Dp,
    val searchBarCornerRadius: Dp,
    val searchBarBorderWidth: Dp,
    val searchBarIconSize: Dp,
    val searchBarClearButtonSize: Dp,
    val searchBarClearIconSize: Dp,
    val searchBarContentPadding: Dp,
    val searchBarIconTextSpacing: Dp,
    val searchBarTextStyle: TextStyle,
    val searchBarDebounceWaitMillis: Long,
    val searchBarAnimationDurationMillis: Int,
    val searchBarBackgroundColor: Color,
    val searchBarDisabledBackgroundColor: Color,
    val searchBarBorderColor: Color,
    val searchBarHoverBorderColor: Color,
    val searchBarFocusBorderColor: Color,
    val searchBarDisabledBorderColor: Color,
    val searchBarPlaceholderColor: Color,
    val searchBarDisabledPlaceholderColor: Color,
    val searchBarTextColor: Color,
    val searchBarDisabledTextColor: Color,
    val searchBarIconColor: Color,
    val searchBarDisabledIconColor: Color,
    val searchBarClearIconColor: Color,
    val searchBarDisabledClearIconColor: Color,
    val searchBarCursorColor: Color,
    val searchBarCancelColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
            control: PaletteControlTokens,
        ): PaletteInputTokens = PaletteInputTokens(
            inputNumberWidth = 220.dp,
            inputNumberButtonWidth = 36.dp,
            inputNumberMinButtonWidth = 32.dp,
            inputNumberAnimationDurationMillis = 100,
            inputNumberDisabledAlpha = opacity.disabled,
            inputNumberButtonColor = colors.surface,
            inputNumberButtonIconColor = colors.textPrimary,
            inputNumberDisabledButtonColor = colors.surface.copy(alpha = opacity.disabled),
            inputNumberDisabledButtonIconColor = colors.textPrimary.copy(alpha = opacity.disabled),
            inputNumberHoverButtonColor = colors.border.copy(alpha = opacity.muted),
            inputNumberContainerColor = colors.surface,
            inputNumberTextColor = colors.textPrimary,
            inputNumberDisabledTextColor = colors.textPrimary.copy(alpha = opacity.disabled),
            inputNumberPlaceholderColor = colors.hint,
            inputNumberCursorColor = colors.primary,
            inputNumberBorderWidth = control.borderWidth,
            inputNumberDividerWidth = control.borderWidth,
            inputNumberTextStyle = typography.body,
            otpCellWidth = 40.dp,
            otpCellHeight = 48.dp,
            otpCellCornerRadius = control.medium.cornerRadius + 2.dp,
            otpCellSpacing = spacing.small,
            otpCellBorderWidth = control.borderWidth,
            otpTextStyle = typography.title.copy(fontSize = 20.sp, textAlign = androidx.compose.ui.text.style.TextAlign.Center),
            otpCursorWidth = 2.dp,
            otpCursorHeight = 24.dp,
            otpCursorBlinkDurationMillis = 1000,
            otpSeparatorWidth = spacing.medium,
            otpDisabledAlpha = opacity.disabled,
            otpAnimationDurationMillis = 100,
            otpFocusedBorderColor = colors.borderFocus,
            otpBorderColor = colors.border,
            otpCellBackgroundColor = colors.surface,
            otpTextColor = colors.textPrimary,
            otpCursorColor = colors.primary,
            otpSeparatorColor = colors.border,
            searchBarHeight = control.large.height,
            searchBarCornerRadius = control.large.cornerRadius,
            searchBarBorderWidth = control.borderWidth,
            searchBarIconSize = control.medium.iconSize,
            searchBarClearButtonSize = control.small.height,
            searchBarClearIconSize = control.small.iconSize,
            searchBarContentPadding = control.small.horizontalPadding,
            searchBarIconTextSpacing = control.medium.verticalPadding,
            searchBarTextStyle = typography.body.copy(fontSize = control.medium.fontSize),
            searchBarDebounceWaitMillis = motion.durationNormal.toLong(),
            searchBarAnimationDurationMillis = motion.durationFast,
            searchBarBackgroundColor = colors.surface,
            searchBarDisabledBackgroundColor = colors.bgDisabled,
            searchBarBorderColor = colors.border,
            searchBarHoverBorderColor = colors.borderHover,
            searchBarFocusBorderColor = colors.borderFocus,
            searchBarDisabledBorderColor = colors.borderDisabled,
            searchBarPlaceholderColor = colors.hint,
            searchBarDisabledPlaceholderColor = colors.hint.copy(alpha = opacity.disabled),
            searchBarTextColor = colors.textPrimary,
            searchBarDisabledTextColor = colors.textPrimary.copy(alpha = opacity.disabled),
            searchBarIconColor = colors.hint,
            searchBarDisabledIconColor = colors.hint.copy(alpha = opacity.disabled),
            searchBarClearIconColor = colors.hint,
            searchBarDisabledClearIconColor = colors.hint.copy(alpha = opacity.disabled),
            searchBarCursorColor = colors.primary,
            searchBarCancelColor = colors.primary,
        )
    }
}

@Immutable
data class PaletteCardTokens(
    val elevatedContainerColor: Color,
    val elevatedContentColor: Color,
    val filledContainerColor: Color,
    val filledContentColor: Color,
    val outlinedContainerColor: Color,
    val outlinedContentColor: Color,
    val outlinedBorderColor: Color,
    val cornerRadius: Dp,
    val contentPadding: Dp,
    val elevation: Dp,
    val borderWidth: Dp,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            elevation: PaletteElevation,
        ): PaletteCardTokens = PaletteCardTokens(
            elevatedContainerColor = colors.surfaceElevated,
            elevatedContentColor = colors.textPrimary,
            filledContainerColor = colors.surface,
            filledContentColor = colors.textPrimary,
            outlinedContainerColor = colors.surface,
            outlinedContentColor = colors.textPrimary,
            outlinedBorderColor = colors.divider,
            cornerRadius = 12.dp,
            contentPadding = spacing.medium,
            elevation = elevation.raised,
            borderWidth = 1.dp,
        )
    }
}

@Immutable
data class PaletteTableTokens(
    val headerContainerColor: Color,
    val headerContentColor: Color,
    val rowContainerColor: Color,
    val rowContentColor: Color,
    val selectedRowContainerColor: Color,
    val selectedRowContentColor: Color,
    val dividerColor: Color,
    val headerHeight: Dp,
    val rowHeight: Dp,
    val paginationHeight: Dp,
    val cellContentPadding: Dp,
    val dividerThickness: Dp,
    val selectionColumnWidth: Dp,
    val sortIconHeight: Dp,
    val emptyContentPadding: Dp,
    val headerTextStyle: TextStyle,
    val bodyTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
        ): PaletteTableTokens = PaletteTableTokens(
            headerContainerColor = colors.surface,
            headerContentColor = colors.textPrimary,
            rowContainerColor = colors.surface,
            rowContentColor = colors.textPrimary,
            selectedRowContainerColor = colors.bgSelected,
            selectedRowContentColor = colors.primary,
            dividerColor = colors.divider,
            headerHeight = 56.dp,
            rowHeight = 52.dp,
            paginationHeight = 56.dp,
            cellContentPadding = spacing.medium,
            dividerThickness = 1.dp,
            selectionColumnWidth = 48.dp,
            sortIconHeight = 16.dp,
            emptyContentPadding = spacing.extraLarge,
            headerTextStyle = typography.title,
            bodyTextStyle = typography.body,
        )
    }
}

@Immutable
data class PaletteDataGridTokens(
    val headerContainerColor: Color,
    val headerContentColor: Color,
    val rowContainerColor: Color,
    val rowContentColor: Color,
    val dividerColor: Color,
    val headerHeight: Dp,
    val rowHeight: Dp,
    val cellPadding: Dp,
    val headerTextStyle: TextStyle,
    val rowTextStyle: TextStyle,
    val defaultPageSize: Int,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
        ): PaletteDataGridTokens = PaletteDataGridTokens(
            headerContainerColor = colors.surface,
            headerContentColor = colors.textPrimary,
            rowContainerColor = colors.surface,
            rowContentColor = colors.textPrimary,
            dividerColor = colors.divider,
            headerHeight = 48.dp,
            rowHeight = 44.dp,
            cellPadding = spacing.small + spacing.extraSmall,
            headerTextStyle = typography.label,
            rowTextStyle = typography.body,
            defaultPageSize = 10,
        )
    }
}

@Immutable
data class PaletteDataDisplayTokens(
    val listDividerColor: Color,
    val listDividerHeight: Dp,
    val listItemHeight: Dp,
    val listContentPadding: Dp,
    val descriptionsLabelColor: Color,
    val descriptionsContentColor: Color,
    val descriptionsDividerColor: Color,
    val descriptionsRowHeight: Dp,
    val descriptionsLabelWidth: Dp,
    val descriptionsPadding: Dp,
    val descriptionsRowSpacing: Dp,
    val descriptionsDividerHeight: Dp,
    val descriptionsTextStyle: TextStyle,
    val badgeContainerColor: Color,
    val badgeContentColor: Color,
    val badgeSmallSize: Dp,
    val badgeMediumSize: Dp,
    val badgeLargeSize: Dp,
    val badgeContentPaddingHorizontal: Dp,
    val badgeTextStyle: TextStyle,
    val avatarBackgroundColor: Color,
    val avatarTextColor: Color,
    val avatarSmallSize: Dp,
    val avatarMediumSize: Dp,
    val avatarLargeSize: Dp,
    val avatarExtraLargeSize: Dp,
    val avatarRoundedCornerRadius: Dp,
    val avatarSmallTextStyle: TextStyle,
    val avatarMediumTextStyle: TextStyle,
    val avatarLargeTextStyle: TextStyle,
    val paginationActiveColor: Color,
    val paginationTextColor: Color,
    val paginationDisabledColor: Color,
    val paginationActiveBackgroundColor: Color,
    val paginationBackgroundColor: Color,
    val paginationDisabledBackgroundColor: Color,
    val paginationMinTouchSize: Dp,
    val paginationSpacing: Dp,
    val paginationContentPaddingHorizontal: Dp,
    val paginationContentPaddingVertical: Dp,
    val paginationCornerRadius: Dp,
    val paginationEllipsisPaddingHorizontal: Dp,
    val paginationTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
        ): PaletteDataDisplayTokens = PaletteDataDisplayTokens(
            listDividerColor = colors.divider,
            listDividerHeight = 1.dp,
            listItemHeight = 56.dp,
            listContentPadding = spacing.medium,
            descriptionsLabelColor = colors.textSecondary,
            descriptionsContentColor = colors.textPrimary,
            descriptionsDividerColor = colors.divider,
            descriptionsRowHeight = 40.dp,
            descriptionsLabelWidth = 120.dp,
            descriptionsPadding = spacing.small + spacing.extraSmall,
            descriptionsRowSpacing = spacing.medium,
            descriptionsDividerHeight = 1.dp,
            descriptionsTextStyle = typography.body,
            badgeContainerColor = colors.error,
            badgeContentColor = colors.onError,
            badgeSmallSize = 12.dp,
            badgeMediumSize = 16.dp,
            badgeLargeSize = 20.dp,
            badgeContentPaddingHorizontal = 6.dp,
            badgeTextStyle = typography.label,
            avatarBackgroundColor = colors.primary,
            avatarTextColor = colors.onPrimary,
            avatarSmallSize = 24.dp,
            avatarMediumSize = 40.dp,
            avatarLargeSize = 56.dp,
            avatarExtraLargeSize = 96.dp,
            avatarRoundedCornerRadius = 8.dp,
            avatarSmallTextStyle = typography.label,
            avatarMediumTextStyle = typography.body,
            avatarLargeTextStyle = typography.title,
            paginationActiveColor = colors.primary,
            paginationTextColor = colors.textPrimary,
            paginationDisabledColor = colors.textDisabled,
            paginationActiveBackgroundColor = colors.bgSelected,
            paginationBackgroundColor = Color.Transparent,
            paginationDisabledBackgroundColor = Color.Transparent,
            paginationMinTouchSize = 48.dp,
            paginationSpacing = spacing.extraSmall,
            paginationContentPaddingHorizontal = spacing.small + spacing.extraSmall,
            paginationContentPaddingVertical = spacing.small,
            paginationCornerRadius = 6.dp,
            paginationEllipsisPaddingHorizontal = spacing.small,
            paginationTextStyle = typography.body,
        )
    }
}

@Immutable
data class PaletteDataEntryTokens(
    val timelineLineColor: Color,
    val timelineDotColor: Color,
    val timelineDotSize: Dp,
    val timelineLineWidth: Dp,
    val timelineDotToContent: Dp,
    val timelineItemSpacing: Dp,
    val transferContainerColor: Color,
    val transferHeaderColor: Color,
    val transferHeaderTextColor: Color,
    val transferItemTextColor: Color,
    val transferDisabledItemTextColor: Color,
    val transferSelectedItemColor: Color,
    val transferButtonColor: Color,
    val transferButtonContentColor: Color,
    val transferDisabledButtonColor: Color,
    val transferWidth: Dp,
    val transferHeight: Dp,
    val transferHeaderHeight: Dp,
    val transferItemHeight: Dp,
    val transferButtonWidth: Dp,
    val transferButtonHeight: Dp,
    val transferButtonSpacing: Dp,
    val transferPanelCornerRadius: Dp,
    val transferPanelBorderWidth: Dp,
    val transferHeaderPaddingHorizontal: Dp,
    val transferRowPaddingHorizontal: Dp,
    val transferSearchHeight: Dp,
    val transferSearchPaddingHorizontal: Dp,
    val transferSearchPaddingVertical: Dp,
    val transferSearchCornerRadius: Dp,
    val transferSearchContainerColor: Color,
    val transferSearchTextColor: Color,
    val transferSearchPlaceholderColor: Color,
    val transferSearchCursorColor: Color,
    val transferTextStyle: TextStyle,
    val transferSearchTextStyle: TextStyle,
    val transferIconSize: Dp,
    val treeNodeHeight: Dp,
    val treeIndent: Dp,
    val treeIconSize: Dp,
    val treeIconTextSpacing: Dp,
    val treeNodeColor: Color,
    val treeSelectedColor: Color,
    val treeSelectedContainerColor: Color,
    val treeIconColor: Color,
    val sortableItemPadding: Dp,
    val sortableItemSpacing: Dp,
    val sortableItemColor: Color,
    val sortableItemTextColor: Color,
    val sortableDragHintColor: Color,
    val sortableTextStyle: TextStyle,
    val virtualListItemHeight: Dp,
    val virtualListItemPadding: Dp,
    val virtualListItemColor: Color,
    val virtualListItemContentColor: Color,
    val virtualListTextStyle: TextStyle,
    val infiniteScrollLoadingPadding: Dp,
    val infiniteScrollTextColor: Color,
    val infiniteScrollTextStyle: TextStyle,
    val uploadBorderColor: Color,
    val uploadBackgroundColor: Color,
    val uploadContentColor: Color,
    val uploadSuccessColor: Color,
    val uploadErrorColor: Color,
    val uploadBorderRadius: Dp,
    val uploadBorderWidth: Dp,
    val uploadContentPadding: Dp,
    val uploadItemSpacing: Dp,
    val uploadTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            control: PaletteControlTokens,
        ): PaletteDataEntryTokens = PaletteDataEntryTokens(
            timelineLineColor = colors.border,
            timelineDotColor = colors.primary,
            timelineDotSize = 8.dp,
            timelineLineWidth = 2.dp,
            timelineDotToContent = spacing.medium,
            timelineItemSpacing = spacing.extraLarge,
            transferContainerColor = colors.surface,
            transferHeaderColor = colors.border,
            transferHeaderTextColor = colors.textPrimary,
            transferItemTextColor = colors.textPrimary,
            transferDisabledItemTextColor = colors.hint,
            transferSelectedItemColor = colors.primary.copy(alpha = opacity.selected),
            transferButtonColor = colors.primary,
            transferButtonContentColor = colors.onPrimary,
            transferDisabledButtonColor = colors.border,
            transferWidth = 200.dp,
            transferHeight = 300.dp,
            transferHeaderHeight = 40.dp,
            transferItemHeight = 36.dp,
            transferButtonWidth = 48.dp,
            transferButtonHeight = 32.dp,
            transferButtonSpacing = spacing.small,
            transferPanelCornerRadius = control.large.cornerRadius,
            transferPanelBorderWidth = control.borderWidth,
            transferHeaderPaddingHorizontal = spacing.small + spacing.extraSmall,
            transferRowPaddingHorizontal = spacing.extraSmall,
            transferSearchHeight = 32.dp,
            transferSearchPaddingHorizontal = spacing.small,
            transferSearchPaddingVertical = spacing.extraSmall,
            transferSearchCornerRadius = control.small.cornerRadius,
            transferSearchContainerColor = colors.border.copy(alpha = opacity.focusRing + opacity.hover),
            transferSearchTextColor = colors.textPrimary,
            transferSearchPlaceholderColor = colors.hint,
            transferSearchCursorColor = colors.primary,
            transferTextStyle = typography.body.copy(fontSize = 14.sp),
            transferSearchTextStyle = typography.label.copy(fontSize = 12.sp),
            transferIconSize = control.small.iconSize,
            treeNodeHeight = 40.dp,
            treeIndent = 24.dp,
            treeIconSize = 16.dp,
            treeIconTextSpacing = spacing.small,
            treeNodeColor = colors.textPrimary,
            treeSelectedColor = colors.primary,
            treeSelectedContainerColor = colors.primary.copy(alpha = opacity.selected),
            treeIconColor = colors.hint,
            sortableItemPadding = spacing.small + spacing.extraSmall,
            sortableItemSpacing = spacing.small,
            sortableItemColor = colors.surface,
            sortableItemTextColor = colors.textPrimary,
            sortableDragHintColor = colors.primary.copy(alpha = opacity.selected),
            sortableTextStyle = typography.body,
            virtualListItemHeight = 44.dp,
            virtualListItemPadding = spacing.small + spacing.extraSmall,
            virtualListItemColor = colors.surface,
            virtualListItemContentColor = colors.textPrimary,
            virtualListTextStyle = typography.body,
            infiniteScrollLoadingPadding = spacing.medium,
            infiniteScrollTextColor = colors.hint,
            infiniteScrollTextStyle = typography.body.copy(fontSize = 14.sp),
            uploadBorderColor = colors.border,
            uploadBackgroundColor = Color.Transparent,
            uploadContentColor = colors.textPrimary,
            uploadSuccessColor = colors.success,
            uploadErrorColor = colors.error,
            uploadBorderRadius = control.large.cornerRadius,
            uploadBorderWidth = control.borderWidth,
            uploadContentPadding = spacing.small + spacing.extraSmall,
            uploadItemSpacing = spacing.small,
            uploadTextStyle = typography.body,
        )
    }
}

@Immutable
data class PaletteNavigationMenuTokens(
    val selectedContainerColor: Color,
    val selectedTextColor: Color,
    val textColor: Color,
    val disabledTextColor: Color,
    val containerColor: Color,
    val subtitleColor: Color,
    val itemPaddingHorizontal: Dp,
    val itemPaddingVertical: Dp,
    val itemCornerRadius: Dp,
    val itemOuterSpacing: Dp,
    val itemTextStyle: TextStyle,
    val contextMenuWidth: Dp,
    val contextMenuItemHeight: Dp,
    val contextMenuCornerRadius: Dp,
    val contextMenuContentPadding: Dp,
    val contextMenuItemPaddingHorizontal: Dp,
    val contextMenuTextStyle: TextStyle,
    val contextMenuAnimationDurationMillis: Int,
    val contextMenuDismissAnimationDurationMillis: Int,
    val contextMenuShadowElevation: Dp,
    val contextMenuDisabledAlpha: Float,
    val commandPaletteWidth: Dp,
    val commandPaletteMaxHeight: Dp,
    val commandPaletteItemPadding: Dp,
    val commandPaletteItemSpacing: Dp,
    val commandPaletteTitleTextStyle: TextStyle,
    val commandPaletteSubtitleTextStyle: TextStyle,
    val commandPaletteHighlightedContainerColor: Color,
    val tabsActiveColor: Color,
    val tabsInactiveColor: Color,
    val tabsDisabledColor: Color,
    val tabsHorizontalPadding: Dp,
    val tabsVerticalPadding: Dp,
    val tabsIndicatorHeight: Dp,
    val tabsItemSpacing: Dp,
    val tabsTextStyle: TextStyle,
    val breadcrumbTextColor: Color,
    val breadcrumbCurrentColor: Color,
    val breadcrumbSeparatorColor: Color,
    val breadcrumbItemSpacing: Dp,
    val breadcrumbTextStyle: TextStyle,
    val stepsDoneColor: Color,
    val stepsCurrentColor: Color,
    val stepsPendingColor: Color,
    val stepsDotTextColor: Color,
    val stepsDotSize: Dp,
    val stepsLineWidth: Dp,
    val stepsLineHeight: Dp,
    val stepsItemSpacing: Dp,
    val stepsRowSpacing: Dp,
    val stepsTitleTopPadding: Dp,
    val stepsTitleDescriptionSpacing: Dp,
    val stepsTitleTextStyle: TextStyle,
    val stepsDescriptionTextStyle: TextStyle,
    val collapseTitleColor: Color,
    val collapseContentColor: Color,
    val collapseIconColor: Color,
    val collapseTitleHeight: Dp,
    val collapseTitleHorizontalPadding: Dp,
    val collapseContentPadding: Dp,
    val collapseTitleTextStyle: TextStyle,
    val collapseAnimationDurationMillis: Int,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
            elevation: PaletteElevation,
        ): PaletteNavigationMenuTokens = PaletteNavigationMenuTokens(
            selectedContainerColor = colors.primary.copy(alpha = opacity.selected),
            selectedTextColor = colors.primary,
            textColor = colors.textPrimary,
            disabledTextColor = colors.textDisabled,
            containerColor = colors.surfaceElevated,
            subtitleColor = colors.textTertiary,
            itemPaddingHorizontal = spacing.small + spacing.extraSmall,
            itemPaddingVertical = 10.dp,
            itemCornerRadius = 8.dp,
            itemOuterSpacing = 2.dp,
            itemTextStyle = typography.body,
            contextMenuWidth = 160.dp,
            contextMenuItemHeight = 50.dp,
            contextMenuCornerRadius = 4.dp,
            contextMenuContentPadding = spacing.small,
            contextMenuItemPaddingHorizontal = spacing.small + spacing.extraSmall,
            contextMenuTextStyle = typography.body.copy(fontSize = 15.sp),
            contextMenuAnimationDurationMillis = motion.durationFast,
            contextMenuDismissAnimationDurationMillis = motion.durationFast + 10,
            contextMenuShadowElevation = elevation.modal,
            contextMenuDisabledAlpha = opacity.muted,
            commandPaletteWidth = 560.dp,
            commandPaletteMaxHeight = 420.dp,
            commandPaletteItemPadding = spacing.small + spacing.extraSmall,
            commandPaletteItemSpacing = spacing.extraSmall,
            commandPaletteTitleTextStyle = typography.body,
            commandPaletteSubtitleTextStyle = typography.label,
            commandPaletteHighlightedContainerColor = colors.primary.copy(alpha = opacity.selected),
            tabsActiveColor = colors.primary,
            tabsInactiveColor = colors.textSecondary,
            tabsDisabledColor = colors.textDisabled,
            tabsHorizontalPadding = 14.dp,
            tabsVerticalPadding = 10.dp,
            tabsIndicatorHeight = 2.dp,
            tabsItemSpacing = spacing.extraSmall,
            tabsTextStyle = typography.body,
            breadcrumbTextColor = colors.textSecondary,
            breadcrumbCurrentColor = colors.textPrimary,
            breadcrumbSeparatorColor = colors.textTertiary,
            breadcrumbItemSpacing = 6.dp,
            breadcrumbTextStyle = typography.body,
            stepsDoneColor = colors.success,
            stepsCurrentColor = colors.primary,
            stepsPendingColor = colors.border,
            stepsDotTextColor = colors.onPrimary,
            stepsDotSize = 20.dp,
            stepsLineWidth = 2.dp,
            stepsLineHeight = 24.dp,
            stepsItemSpacing = 10.dp,
            stepsRowSpacing = spacing.small,
            stepsTitleTopPadding = 2.dp,
            stepsTitleDescriptionSpacing = 2.dp,
            stepsTitleTextStyle = typography.body,
            stepsDescriptionTextStyle = typography.label,
            collapseTitleColor = colors.textPrimary,
            collapseContentColor = colors.textPrimary,
            collapseIconColor = colors.hint,
            collapseTitleHeight = 48.dp,
            collapseTitleHorizontalPadding = spacing.medium,
            collapseContentPadding = spacing.medium,
            collapseTitleTextStyle = typography.title,
            collapseAnimationDurationMillis = motion.durationNormal,
        )
    }
}

@Immutable
data class PaletteAppBarTokens(
    val toolbarBackgroundColor: Color,
    val toolbarContentColor: Color,
    val toolbarHeight: Dp,
    val toolbarIconSize: Dp,
    val toolbarTitleTextStyle: TextStyle,
    val pageHeaderBackgroundColor: Color,
    val pageHeaderTitleColor: Color,
    val pageHeaderSubtitleColor: Color,
    val pageHeaderBackColor: Color,
    val pageHeaderHeight: Dp,
    val pageHeaderPadding: Dp,
    val pageHeaderBackIconSize: Dp,
    val pageHeaderBackSpacing: Dp,
    val pageHeaderBackSectionSpacing: Dp,
    val pageHeaderTitleTextStyle: TextStyle,
    val pageHeaderSubtitleTextStyle: TextStyle,
    val pageHeaderBackTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
        ): PaletteAppBarTokens = PaletteAppBarTokens(
            toolbarBackgroundColor = colors.primary,
            toolbarContentColor = colors.onPrimary,
            toolbarHeight = 58.dp,
            toolbarIconSize = 24.dp,
            toolbarTitleTextStyle = typography.title.copy(fontSize = 20.sp),
            pageHeaderBackgroundColor = colors.surface,
            pageHeaderTitleColor = colors.textPrimary,
            pageHeaderSubtitleColor = colors.textTertiary,
            pageHeaderBackColor = colors.primary,
            pageHeaderHeight = 56.dp,
            pageHeaderPadding = spacing.medium,
            pageHeaderBackIconSize = 20.dp,
            pageHeaderBackSpacing = spacing.extraSmall,
            pageHeaderBackSectionSpacing = spacing.medium,
            pageHeaderTitleTextStyle = typography.title.copy(fontSize = 18.sp, fontWeight = FontWeight.Bold),
            pageHeaderSubtitleTextStyle = typography.body.copy(fontSize = 14.sp),
            pageHeaderBackTextStyle = typography.body.copy(fontSize = 18.sp),
        )
    }
}

@Immutable
data class PaletteFloatingLayerTokens(
    val tooltipBackgroundColor: Color,
    val tooltipTextColor: Color,
    val tooltipCornerRadius: Dp,
    val tooltipHorizontalPadding: Dp,
    val tooltipVerticalPadding: Dp,
    val tooltipOffsetY: Dp,
    val tooltipMaxWidth: Dp,
    val tooltipTextStyle: TextStyle,
    val popoverContainerColor: Color,
    val popoverBorderColor: Color,
    val popoverCornerRadius: Dp,
    val popoverBorderWidth: Dp,
    val popoverElevation: Dp,
    val popoverPadding: Dp,
    val popoverOffset: Dp,
    val popconfirmContainerColor: Color,
    val popconfirmTitleColor: Color,
    val popconfirmDescriptionColor: Color,
    val popconfirmCornerRadius: Dp,
    val popconfirmPadding: Dp,
    val popconfirmTitleTextStyle: TextStyle,
    val popconfirmDescriptionTextStyle: TextStyle,
    val popconfirmDescriptionSpacing: Dp,
    val popconfirmButtonSpacing: Dp,
    val popconfirmElevation: Dp,
    val popconfirmMaxWidth: Dp,
    val tourContainerColor: Color,
    val tourTitleColor: Color,
    val tourDescriptionColor: Color,
    val tourCornerRadius: Dp,
    val tourContentPadding: Dp,
    val tourTitleTextStyle: TextStyle,
    val tourDescriptionTextStyle: TextStyle,
    val tourItemSpacing: Dp,
    val tourButtonSpacing: Dp,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            elevation: PaletteElevation,
            darkTheme: Boolean,
        ): PaletteFloatingLayerTokens = PaletteFloatingLayerTokens(
            tooltipBackgroundColor = colors.textPrimary.copy(
                alpha = if (darkTheme) opacity.elevatedSurface else opacity.disabledStrong + opacity.hover + opacity.hover,
            ),
            tooltipTextColor = colors.surface,
            tooltipCornerRadius = 6.dp,
            tooltipHorizontalPadding = 10.dp,
            tooltipVerticalPadding = 6.dp,
            tooltipOffsetY = spacing.small,
            tooltipMaxWidth = 320.dp,
            tooltipTextStyle = typography.label,
            popoverContainerColor = colors.surface,
            popoverBorderColor = colors.border,
            popoverCornerRadius = 10.dp,
            popoverBorderWidth = 1.dp,
            popoverElevation = 6.dp,
            popoverPadding = spacing.small + spacing.extraSmall,
            popoverOffset = spacing.small + spacing.extraSmall,
            popconfirmContainerColor = colors.surface,
            popconfirmTitleColor = colors.textPrimary,
            popconfirmDescriptionColor = colors.hint,
            popconfirmCornerRadius = 8.dp,
            popconfirmPadding = spacing.small + spacing.extraSmall,
            popconfirmTitleTextStyle = typography.body.copy(fontSize = 14.sp, fontWeight = FontWeight.Bold),
            popconfirmDescriptionTextStyle = typography.label.copy(fontSize = 12.sp),
            popconfirmDescriptionSpacing = spacing.extraSmall,
            popconfirmButtonSpacing = spacing.small,
            popconfirmElevation = elevation.raised,
            popconfirmMaxWidth = 280.dp,
            tourContainerColor = colors.surface,
            tourTitleColor = colors.textPrimary,
            tourDescriptionColor = colors.hint,
            tourCornerRadius = 10.dp,
            tourContentPadding = 14.dp,
            tourTitleTextStyle = typography.body.copy(fontWeight = FontWeight.Medium),
            tourDescriptionTextStyle = typography.body,
            tourItemSpacing = 14.dp,
            tourButtonSpacing = 14.dp,
        )
    }
}

@Immutable
data class PaletteDialogTokens(
    val containerColor: Color,
    val titleColor: Color,
    val contentColor: Color,
    val cancelColor: Color,
    val okColor: Color,
    val dividerColor: Color,
    val borderRadius: Dp,
    val widthFraction: Float,
    val titlePaddingTop: Dp,
    val titlePaddingBottom: Dp,
    val contentPaddingBottom: Dp,
    val horizontalPadding: Dp,
    val buttonHeight: Dp,
    val dividerWidth: Dp,
    val titleTextStyle: TextStyle,
    val contentTextStyle: TextStyle,
    val buttonTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
        ): PaletteDialogTokens = PaletteDialogTokens(
            containerColor = colors.surfaceElevated,
            titleColor = colors.textPrimary,
            contentColor = colors.textPrimary,
            cancelColor = colors.textPrimary,
            okColor = colors.primary,
            dividerColor = colors.divider,
            borderRadius = 12.dp,
            widthFraction = 0.8f,
            titlePaddingTop = spacing.extraLarge,
            titlePaddingBottom = spacing.medium,
            contentPaddingBottom = spacing.extraLarge,
            horizontalPadding = spacing.large,
            buttonHeight = 56.dp,
            dividerWidth = 0.5.dp,
            titleTextStyle = typography.body.copy(fontSize = 17.sp, fontWeight = FontWeight.Bold),
            contentTextStyle = typography.body.copy(fontSize = 17.sp),
            buttonTextStyle = typography.body.copy(fontSize = 17.sp, fontWeight = FontWeight.Bold),
        )
    }
}

@Immutable
data class PaletteDrawerTokens(
    val containerColor: Color,
    val overlayColor: Color,
    val width: Dp,
    val elevation: Dp,
    val contentPadding: Dp,
    val animationDurationMillis: Int,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            opacity: PaletteOpacity,
            elevation: PaletteElevation,
            motion: PaletteMotion,
        ): PaletteDrawerTokens = PaletteDrawerTokens(
            containerColor = colors.surfaceElevated,
            overlayColor = colors.onSurface.copy(alpha = opacity.overlay),
            width = 320.dp,
            elevation = elevation.modal,
            contentPadding = spacing.medium,
            animationDurationMillis = motion.overlayEnter,
        )
    }
}

@Immutable
data class PalettePopupTokens(
    val containerColor: Color,
    val titleColor: Color,
    val draggableLineColor: Color,
    val cornerRadius: Dp,
    val contentPadding: Dp,
    val draggableLineLength: Dp,
    val draggableLineThickness: Dp,
    val draggableLineOffset: Dp,
    val titleHeight: Dp,
    val titleTextStyle: TextStyle,
    val animationDurationMillis: Int,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            motion: PaletteMotion,
        ): PalettePopupTokens = PalettePopupTokens(
            containerColor = colors.surfaceElevated,
            titleColor = colors.textPrimary,
            draggableLineColor = colors.border,
            cornerRadius = 12.dp,
            contentPadding = spacing.small + spacing.extraSmall,
            draggableLineLength = 40.dp,
            draggableLineThickness = 4.dp,
            draggableLineOffset = -(12).dp,
            titleHeight = 50.dp,
            titleTextStyle = typography.body.copy(fontSize = 17.sp, fontWeight = FontWeight.Bold),
            animationDurationMillis = motion.durationFast,
        )
    }
}

@Immutable
data class PaletteActionSheetTokens(
    val containerColor: Color,
    val titleColor: Color,
    val itemTextColor: Color,
    val descriptionColor: Color,
    val cancelTextColor: Color,
    val dividerColor: Color,
    val dangerColor: Color,
    val itemHeight: Dp,
    val titleHeight: Dp,
    val iconSpacing: Dp,
    val itemPadding: Dp,
    val gapHeight: Dp,
    val cancelHeight: Dp,
    val dividerThickness: Dp,
    val disabledAlpha: Float,
    val titleTextStyle: TextStyle,
    val itemTextStyle: TextStyle,
    val descriptionTextStyle: TextStyle,
    val cancelTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
        ): PaletteActionSheetTokens = PaletteActionSheetTokens(
            containerColor = colors.surfaceElevated,
            titleColor = colors.textTertiary,
            itemTextColor = colors.textPrimary,
            descriptionColor = colors.textTertiary,
            cancelTextColor = colors.textPrimary,
            dividerColor = colors.divider,
            dangerColor = colors.error,
            itemHeight = 56.dp,
            titleHeight = 56.dp,
            iconSpacing = spacing.small - 2.dp,
            itemPadding = spacing.small + spacing.extraSmall,
            gapHeight = spacing.small,
            cancelHeight = 56.dp,
            dividerThickness = 0.5.dp,
            disabledAlpha = opacity.muted,
            titleTextStyle = typography.label.copy(fontSize = 12.sp),
            itemTextStyle = typography.body.copy(fontSize = 17.sp),
            descriptionTextStyle = typography.label.copy(fontSize = 12.sp),
            cancelTextStyle = typography.body.copy(fontSize = 17.sp),
        )
    }
}

@Immutable
data class PaletteMessageTokens(
    val infoColor: Color,
    val successColor: Color,
    val warningColor: Color,
    val errorColor: Color,
    val containerColor: Color,
    val infoBorderColor: Color,
    val successBorderColor: Color,
    val warningBorderColor: Color,
    val errorBorderColor: Color,
    val defaultDurationMillis: Long,
    val animationDurationMillis: Int,
    val topPadding: Dp,
    val screenHorizontalPadding: Dp,
    val horizontalPadding: Dp,
    val verticalPadding: Dp,
    val borderRadius: Dp,
    val borderWidth: Dp,
    val iconSize: Dp,
    val iconSpacing: Dp,
    val textStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
        ): PaletteMessageTokens = PaletteMessageTokens(
            infoColor = colors.info,
            successColor = colors.success,
            warningColor = colors.warning,
            errorColor = colors.error,
            containerColor = colors.surfaceOverlay,
            infoBorderColor = colors.info.copy(alpha = opacity.muted),
            successBorderColor = colors.success.copy(alpha = opacity.disabled),
            warningBorderColor = colors.warning.copy(alpha = opacity.disabled),
            errorBorderColor = colors.error.copy(alpha = opacity.disabled),
            defaultDurationMillis = 2500L,
            animationDurationMillis = motion.overlayEnter,
            topPadding = 20.dp,
            screenHorizontalPadding = spacing.medium,
            horizontalPadding = 14.dp,
            verticalPadding = 10.dp,
            borderRadius = 8.dp,
            borderWidth = 1.dp,
            iconSize = 18.dp,
            iconSpacing = spacing.small,
            textStyle = typography.body,
        )
    }
}

@Immutable
data class PaletteNotificationTokens(
    val infoColor: Color,
    val successColor: Color,
    val warningColor: Color,
    val errorColor: Color,
    val containerColor: Color,
    val titleColor: Color,
    val contentColor: Color,
    val borderAlpha: Float,
    val defaultDurationMillis: Long,
    val animationDurationMillis: Int,
    val topPadding: Dp,
    val endPadding: Dp,
    val horizontalPadding: Dp,
    val verticalPadding: Dp,
    val cornerRadius: Dp,
    val borderWidth: Dp,
    val minWidth: Dp,
    val maxWidth: Dp,
    val iconSize: Dp,
    val closeIconSize: Dp,
    val titleSpacing: Dp,
    val contentSpacing: Dp,
    val titleTextStyle: TextStyle,
    val contentTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
            darkTheme: Boolean,
        ): PaletteNotificationTokens = PaletteNotificationTokens(
            infoColor = colors.info,
            successColor = colors.success,
            warningColor = colors.warning,
            errorColor = colors.error,
            containerColor = if (darkTheme) colors.surfaceOverlay else colors.surface,
            titleColor = colors.textPrimary,
            contentColor = colors.textSecondary,
            borderAlpha = opacity.muted,
            defaultDurationMillis = 3500L,
            animationDurationMillis = motion.overlayEnter,
            topPadding = 20.dp,
            endPadding = spacing.medium,
            horizontalPadding = spacing.medium,
            verticalPadding = spacing.small + spacing.extraSmall,
            cornerRadius = 10.dp,
            borderWidth = 1.dp,
            minWidth = 260.dp,
            maxWidth = 380.dp,
            iconSize = 20.dp,
            closeIconSize = 20.dp,
            titleSpacing = spacing.small,
            contentSpacing = 6.dp,
            titleTextStyle = typography.body.copy(fontWeight = FontWeight.Medium),
            contentTextStyle = typography.body,
        )
    }
}

@Immutable
data class PaletteToastTokens(
    val backgroundColor: Color,
    val textColor: Color,
    val iconSize: Dp,
    val noIconWidth: Dp,
    val noIconMinHeight: Dp,
    val iconBorderRadius: Dp,
    val noIconBorderRadius: Dp,
    val loadingSize: Dp,
    val iconSpacing: Dp,
    val textPaddingHorizontal: Dp,
    val textPaddingVertical: Dp,
    val iconTextStyle: TextStyle,
    val noIconTextStyle: TextStyle,
    val iconTextMaxWidthPx: Int,
    val animationDurationMillis: Int,
    val exitDelayMillis: Long,
    val defaultDurationMillis: Long,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            motion: PaletteMotion,
            darkTheme: Boolean,
        ): PaletteToastTokens = PaletteToastTokens(
            backgroundColor = if (darkTheme) colors.inverseSurface.copy(alpha = 0.16f) else colors.inverseSurface.copy(alpha = 0.7f),
            textColor = if (darkTheme) colors.textPrimary else colors.inverseOnSurface,
            iconSize = 136.dp,
            noIconWidth = 152.dp,
            noIconMinHeight = 44.dp,
            iconBorderRadius = 12.dp,
            noIconBorderRadius = 8.dp,
            loadingSize = 43.dp,
            iconSpacing = 10.dp,
            textPaddingHorizontal = spacing.small + spacing.extraSmall,
            textPaddingVertical = 6.dp,
            iconTextStyle = typography.body.copy(fontSize = 17.sp),
            noIconTextStyle = typography.body,
            iconTextMaxWidthPx = 354,
            animationDurationMillis = 100,
            exitDelayMillis = motion.durationFast.toLong(),
            defaultDurationMillis = 1500L,
        )
    }
}

@Immutable
data class PaletteTagSizeTokens(
    val height: Dp,
    val horizontalPadding: Dp,
    val cornerRadius: Dp,
    val closeButtonSize: Dp,
    val fontSize: TextUnit,
)

@Immutable
data class PaletteTagTokens(
    val defaultContainerColor: Color,
    val defaultContentColor: Color,
    val defaultBorderColor: Color,
    val outlinedContainerColor: Color,
    val outlinedContentColor: Color,
    val outlinedBorderColor: Color,
    val successContainerColor: Color,
    val successContentColor: Color,
    val warningContainerColor: Color,
    val warningContentColor: Color,
    val errorContainerColor: Color,
    val errorContentColor: Color,
    val infoContainerColor: Color,
    val infoContentColor: Color,
    val pastelContentColor: Color,
    val borderWidth: Dp,
    val itemSpacing: Dp,
    val closeIconScale: Float,
    val small: PaletteTagSizeTokens,
    val medium: PaletteTagSizeTokens,
    val large: PaletteTagSizeTokens,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            opacity: PaletteOpacity,
        ): PaletteTagTokens = PaletteTagTokens(
            defaultContainerColor = colors.primary.copy(alpha = opacity.selected),
            defaultContentColor = colors.primary,
            defaultBorderColor = Color.Transparent,
            outlinedContainerColor = Color.Transparent,
            outlinedContentColor = colors.textPrimary,
            outlinedBorderColor = colors.border,
            successContainerColor = colors.success.copy(alpha = opacity.selected),
            successContentColor = colors.success,
            warningContainerColor = colors.warning.copy(alpha = opacity.selected),
            warningContentColor = colors.warning,
            errorContainerColor = colors.error.copy(alpha = opacity.selected),
            errorContentColor = colors.error,
            infoContainerColor = colors.info.copy(alpha = opacity.selected),
            infoContentColor = colors.info,
            pastelContentColor = colors.textSecondary,
            borderWidth = 1.dp,
            itemSpacing = spacing.extraSmall,
            closeIconScale = 0.7f,
            small = PaletteTagSizeTokens(
                height = 24.dp,
                horizontalPadding = spacing.small,
                cornerRadius = 12.dp,
                closeButtonSize = 14.dp,
                fontSize = 12.sp,
            ),
            medium = PaletteTagSizeTokens(
                height = 32.dp,
                horizontalPadding = 12.dp,
                cornerRadius = 16.dp,
                closeButtonSize = 18.dp,
                fontSize = 14.sp,
            ),
            large = PaletteTagSizeTokens(
                height = 40.dp,
                horizontalPadding = spacing.medium,
                cornerRadius = 20.dp,
                closeButtonSize = 22.dp,
                fontSize = 16.sp,
            ),
        )
    }
}

@Immutable
data class PaletteFeedbackDisplayTokens(
    val infoColor: Color,
    val successColor: Color,
    val warningColor: Color,
    val errorColor: Color,
    val neutralColor: Color,
    val titleColor: Color,
    val bodyColor: Color,
    val subtleColor: Color,
    val alertInfoContainerColor: Color,
    val alertSuccessContainerColor: Color,
    val alertWarningContainerColor: Color,
    val alertErrorContainerColor: Color,
    val alertInfoBorderColor: Color,
    val alertSuccessBorderColor: Color,
    val alertWarningBorderColor: Color,
    val alertErrorBorderColor: Color,
    val alertCornerRadius: Dp,
    val alertContentPadding: Dp,
    val alertIconSize: Dp,
    val alertIconSpacing: Dp,
    val alertCloseIconSize: Dp,
    val alertBorderWidth: Dp,
    val alertMessageDescriptionSpacing: Dp,
    val alertDescriptionAlpha: Float,
    val alertCloseIconAlpha: Float,
    val alertMessageTextStyle: TextStyle,
    val alertDescriptionTextStyle: TextStyle,
    val resultIconSize: Dp,
    val resultTitleTextStyle: TextStyle,
    val resultSubtitleTextStyle: TextStyle,
    val resultIconToTitleSpacing: Dp,
    val resultTitleToSubtitleSpacing: Dp,
    val resultSubtitleToExtraSpacing: Dp,
    val emptyIconSize: Dp,
    val emptyIconToTitleSpacing: Dp,
    val emptyTitleToDescriptionSpacing: Dp,
    val emptyDescriptionToActionSpacing: Dp,
    val emptyTitleTextStyle: TextStyle,
    val emptyDescriptionTextStyle: TextStyle,
    val statisticTrendIconSize: Dp,
    val statisticSpacing: Dp,
    val statisticRowItemSpacing: Dp,
    val statisticValueColor: Color,
    val statisticTitleColor: Color,
    val statisticTrendUpColor: Color,
    val statisticTrendDownColor: Color,
    val statisticValueTextStyle: TextStyle,
    val statisticTitleTextStyle: TextStyle,
    val statisticTrendTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
        ): PaletteFeedbackDisplayTokens {
            val alertContainerAlpha = opacity.hover
            val alertBorderAlpha = opacity.focusRing + opacity.hover + opacity.hover / 4f
            return PaletteFeedbackDisplayTokens(
                infoColor = colors.info,
                successColor = colors.success,
                warningColor = colors.warning,
                errorColor = colors.error,
                neutralColor = colors.textTertiary,
                titleColor = colors.textPrimary,
                bodyColor = colors.textPrimary,
                subtleColor = colors.textTertiary,
                alertInfoContainerColor = colors.info.copy(alpha = alertContainerAlpha),
                alertSuccessContainerColor = colors.success.copy(alpha = alertContainerAlpha),
                alertWarningContainerColor = colors.warning.copy(alpha = alertContainerAlpha),
                alertErrorContainerColor = colors.error.copy(alpha = alertContainerAlpha),
                alertInfoBorderColor = colors.info.copy(alpha = alertBorderAlpha),
                alertSuccessBorderColor = colors.success.copy(alpha = alertBorderAlpha),
                alertWarningBorderColor = colors.warning.copy(alpha = alertBorderAlpha),
                alertErrorBorderColor = colors.error.copy(alpha = alertBorderAlpha),
                alertCornerRadius = 8.dp,
                alertContentPadding = spacing.small + spacing.extraSmall,
                alertIconSize = 16.dp,
                alertIconSpacing = spacing.small,
                alertCloseIconSize = 16.dp,
                alertBorderWidth = 1.dp,
                alertMessageDescriptionSpacing = spacing.extraSmall,
                alertDescriptionAlpha = 1f - opacity.focusRing,
                alertCloseIconAlpha = opacity.subtle,
                alertMessageTextStyle = typography.body.copy(fontSize = 14.sp, fontWeight = FontWeight.Bold),
                alertDescriptionTextStyle = typography.body.copy(fontSize = 14.sp),
                resultIconSize = 64.dp,
                resultTitleTextStyle = typography.title.copy(fontSize = 20.sp, fontWeight = FontWeight.Bold),
                resultSubtitleTextStyle = typography.body.copy(fontSize = 14.sp),
                resultIconToTitleSpacing = spacing.medium,
                resultTitleToSubtitleSpacing = spacing.small,
                resultSubtitleToExtraSpacing = spacing.large,
                emptyIconSize = 64.dp,
                emptyIconToTitleSpacing = spacing.medium,
                emptyTitleToDescriptionSpacing = spacing.small,
                emptyDescriptionToActionSpacing = spacing.large,
                emptyTitleTextStyle = typography.title,
                emptyDescriptionTextStyle = typography.body,
                statisticTrendIconSize = 16.dp,
                statisticSpacing = spacing.small,
                statisticRowItemSpacing = spacing.extraSmall,
                statisticValueColor = colors.textPrimary,
                statisticTitleColor = colors.textSecondary,
                statisticTrendUpColor = colors.success,
                statisticTrendDownColor = colors.error,
                statisticValueTextStyle = typography.title,
                statisticTitleTextStyle = typography.body,
                statisticTrendTextStyle = typography.body,
            )
        }
    }
}

@Immutable
data class PaletteProgressTokens(
    val progressColor: Color,
    val trackColor: Color,
    val textColor: Color,
    val linearHeight: Dp,
    val linearContainerHeight: Dp,
    val circleSize: Dp,
    val circleStrokeWidth: Dp,
    val circleVerticalPadding: Dp,
    val textStyle: TextStyle,
    val dashboardTextStyle: TextStyle,
    val labelWidth: Dp,
    val labelSpacing: Dp,
    val progressAnimationDurationMillis: Int,
    val dashboardSize: Dp,
    val dashboardStrokeWidth: Dp,
    val dashboardStartAngle: Float,
    val dashboardSweepAngle: Float,
    val loadingColor: Color,
    val loadingOutlineColor: Color,
    val loadingOnPrimaryColor: Color,
    val loadingSize: Dp,
    val loadingDotSize: Dp,
    val loadingStrokeWidth: Dp,
    val loadingMobileSize: Dp,
    val loadingWebSize: Dp,
    val loadingMultipointWidth: Dp,
    val loadingMultipointHeight: Dp,
    val loadingMinDotsWidth: Dp,
    val loadingCircleOrbitInset: Dp,
    val loadingBounceOffset: Dp,
    val loadingActiveDotAlpha: Float,
    val loadingInactiveDotAlpha: Float,
    val loadingDotsAnimationDurationMillis: Int,
    val loadingBarsAnimationDurationMillis: Int,
    val loadingBarsDelayMillis: Int,
    val loadingCircleAnimationDurationMillis: Int,
    val skeletonBackgroundColor: Color,
    val skeletonShimmerStartColor: Color,
    val skeletonShimmerCenterColor: Color,
    val skeletonShimmerEndColor: Color,
    val skeletonCircleSize: Dp,
    val skeletonSquareSize: Dp,
    val skeletonSquareBorderRadius: Dp,
    val skeletonRectangleHeight: Dp,
    val skeletonRectangleBorderRadius: Dp,
    val skeletonLineLongWidth: Dp,
    val skeletonLineShortWidth: Dp,
    val skeletonLineHeight: Dp,
    val skeletonLineBorderRadius: Dp,
    val skeletonShimmerAnimationDurationMillis: Int,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            motion: PaletteMotion,
            darkTheme: Boolean,
        ): PaletteProgressTokens = PaletteProgressTokens(
            progressColor = colors.primary,
            trackColor = colors.border,
            textColor = colors.textPrimary,
            linearHeight = 3.dp,
            linearContainerHeight = 66.dp,
            circleSize = 100.dp,
            circleStrokeWidth = 6.dp,
            circleVerticalPadding = 20.dp,
            textStyle = typography.body.copy(fontSize = 14.sp),
            dashboardTextStyle = typography.body.copy(fontSize = 16.sp),
            labelWidth = 40.dp,
            labelSpacing = spacing.small + 2.dp,
            progressAnimationDurationMillis = motion.durationNormal,
            dashboardSize = 100.dp,
            dashboardStrokeWidth = 6.dp,
            dashboardStartAngle = 135f,
            dashboardSweepAngle = 270f,
            loadingColor = colors.primary,
            loadingOutlineColor = colors.border,
            loadingOnPrimaryColor = colors.onPrimary,
            loadingSize = 16.dp,
            loadingDotSize = 4.dp,
            loadingStrokeWidth = 2.dp,
            loadingMobileSize = 34.dp,
            loadingWebSize = 24.dp,
            loadingMultipointWidth = 44.dp,
            loadingMultipointHeight = 20.dp,
            loadingMinDotsWidth = 32.dp,
            loadingCircleOrbitInset = spacing.small,
            loadingBounceOffset = 3.dp,
            loadingActiveDotAlpha = 1f - opacity.focusRing,
            loadingInactiveDotAlpha = opacity.muted,
            loadingDotsAnimationDurationMillis = 1000,
            loadingBarsAnimationDurationMillis = motion.overlayEnter + motion.overlayExit + 40,
            loadingBarsDelayMillis = 100,
            loadingCircleAnimationDurationMillis = 1200,
            skeletonBackgroundColor = colors.textPrimary.copy(alpha = if (darkTheme) opacity.selected else opacity.hover),
            skeletonShimmerStartColor = colors.textPrimary.copy(alpha = opacity.selected),
            skeletonShimmerCenterColor = colors.textPrimary.copy(alpha = opacity.hover / 2f),
            skeletonShimmerEndColor = colors.textPrimary.copy(alpha = opacity.selected),
            skeletonCircleSize = 100.dp,
            skeletonSquareSize = 100.dp,
            skeletonSquareBorderRadius = spacing.large,
            skeletonRectangleHeight = 200.dp,
            skeletonRectangleBorderRadius = spacing.large,
            skeletonLineLongWidth = 200.dp,
            skeletonLineShortWidth = 100.dp,
            skeletonLineHeight = 30.dp,
            skeletonLineBorderRadius = spacing.small,
            skeletonShimmerAnimationDurationMillis = 1000,
        )
    }
}

@Immutable
data class PaletteMediaTokens(
    val carouselHeight: Dp,
    val carouselIndicatorSize: Dp,
    val carouselActiveIndicatorSize: Dp,
    val carouselInactiveIndicatorSize: Dp,
    val carouselIndicatorSpacing: Dp,
    val carouselArrowContainerSize: Dp,
    val carouselArrowInset: Dp,
    val carouselIndicatorBottomPadding: Dp,
    val carouselIndicatorColor: Color,
    val carouselActiveIndicatorColor: Color,
    val carouselArrowContainerColor: Color,
    val carouselArrowContentColor: Color,
    val imageCornerRadius: Dp,
    val imageContainerColor: Color,
    val imagePreviewOverlayColor: Color,
    val colorPickerPanelWidth: Dp,
    val colorPickerPanelHeight: Dp,
    val colorPickerHueBarHeight: Dp,
    val colorPickerAlphaBarHeight: Dp,
    val colorPickerPreviewSize: Dp,
    val colorPickerCornerRadius: Dp,
    val colorPickerThumbSize: Dp,
    val colorPickerPresetColorSize: Dp,
    val colorPickerPresetColorSpacing: Dp,
    val colorPickerBarSpacing: Dp,
    val colorPickerHexInputWidth: Dp,
    val colorPickerHexInputHeight: Dp,
    val colorPickerInputCornerRadius: Dp,
    val colorPickerInputBorderWidth: Dp,
    val colorPickerInputPaddingHorizontal: Dp,
    val colorPickerInputPaddingVertical: Dp,
    val colorPickerInputTextStyle: TextStyle,
    val colorPickerInputTextColor: Color,
    val colorPickerInputBorderColor: Color,
    val colorPickerInputCursorColor: Color,
    val colorPickerSelectedBorderColor: Color,
    val colorPickerThumbFillColor: Color,
    val colorPickerThumbBorderColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            control: PaletteControlTokens,
        ): PaletteMediaTokens = PaletteMediaTokens(
            carouselHeight = 200.dp,
            carouselIndicatorSize = 8.dp,
            carouselActiveIndicatorSize = 10.dp,
            carouselInactiveIndicatorSize = 6.dp,
            carouselIndicatorSpacing = spacing.small,
            carouselArrowContainerSize = 40.dp,
            carouselArrowInset = spacing.medium,
            carouselIndicatorBottomPadding = spacing.medium,
            carouselIndicatorColor = colors.textPrimary.copy(alpha = opacity.muted - opacity.hover),
            carouselActiveIndicatorColor = colors.primary,
            carouselArrowContainerColor = colors.surface.copy(alpha = opacity.subtle),
            carouselArrowContentColor = colors.textPrimary,
            imageCornerRadius = control.large.cornerRadius,
            imageContainerColor = colors.surface,
            imagePreviewOverlayColor = Color.Black.copy(alpha = opacity.elevatedSurface),
            colorPickerPanelWidth = 240.dp,
            colorPickerPanelHeight = 160.dp,
            colorPickerHueBarHeight = 16.dp,
            colorPickerAlphaBarHeight = 16.dp,
            colorPickerPreviewSize = 32.dp,
            colorPickerCornerRadius = control.large.cornerRadius,
            colorPickerThumbSize = 12.dp,
            colorPickerPresetColorSize = 24.dp,
            colorPickerPresetColorSpacing = spacing.extraSmall,
            colorPickerBarSpacing = spacing.small + spacing.extraSmall,
            colorPickerHexInputWidth = 80.dp,
            colorPickerHexInputHeight = 28.dp,
            colorPickerInputCornerRadius = control.small.cornerRadius,
            colorPickerInputBorderWidth = control.borderWidth,
            colorPickerInputPaddingHorizontal = 6.dp,
            colorPickerInputPaddingVertical = spacing.extraSmall,
            colorPickerInputTextStyle = typography.label.copy(fontSize = 12.sp),
            colorPickerInputTextColor = colors.textPrimary,
            colorPickerInputBorderColor = colors.border,
            colorPickerInputCursorColor = colors.primary,
            colorPickerSelectedBorderColor = colors.primary,
            colorPickerThumbFillColor = Color.White,
            colorPickerThumbBorderColor = Color.Black,
        )
    }
}

@Immutable
data class PaletteUtilityTokens(
    val qrCodeSize: Dp,
    val qrCodeColor: Color,
    val qrCodeBackgroundColor: Color,
    val barcodeWidth: Dp,
    val barcodeHeight: Dp,
    val barcodeColor: Color,
    val barcodeBackgroundColor: Color,
    val watermarkColor: Color,
    val watermarkTextStyle: TextStyle,
    val watermarkRotate: Float,
    val watermarkGapX: Dp,
    val watermarkGapY: Dp,
    val watermarkAlpha: Float,
    val codeBlockBackgroundColor: Color,
    val codeBlockBorderColor: Color,
    val codeBlockContentColor: Color,
    val codeBlockKeywordColor: Color,
    val codeBlockStringColor: Color,
    val codeBlockNumberColor: Color,
    val codeBlockCommentColor: Color,
    val codeBlockFunctionColor: Color,
    val codeBlockTypeColor: Color,
    val codeBlockAnnotationColor: Color,
    val codeBlockOperatorColor: Color,
    val codeBlockPunctuationColor: Color,
    val codeBlockLineNumberColor: Color,
    val codeBlockHighlightedLineColor: Color,
    val codeBlockHeaderBackgroundColor: Color,
    val codeBlockTextStyle: TextStyle,
    val codeBlockCornerRadius: Dp,
    val codeBlockBorderWidth: Dp,
    val codeBlockPadding: Dp,
    val markdownBlockSpacing: Dp,
    val markdownEditorMinHeight: Dp,
    val mermaidNodeContainerColor: Color,
    val mermaidNodeBorderColor: Color,
    val mermaidNodeContentColor: Color,
    val mermaidEdgeColor: Color,
    val mermaidNodeCornerRadius: Dp,
    val mermaidEntityHeaderColor: Color,
    val mermaidPrimaryKeyColor: Color,
    val mermaidForeignKeyColor: Color,
    /** Sequence-diagram note fill — warm tint derived from warning semantics. */
    val mermaidNoteColor: Color,
    /** Sequence-diagram note outline — stronger warm tint. */
    val mermaidNoteBorderColor: Color,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            opacity: PaletteOpacity,
            control: PaletteControlTokens,
        ): PaletteUtilityTokens = PaletteUtilityTokens(
            qrCodeSize = 120.dp,
            qrCodeColor = Color.Black,
            qrCodeBackgroundColor = Color.White,
            barcodeWidth = 180.dp,
            barcodeHeight = 80.dp,
            barcodeColor = Color.Black,
            barcodeBackgroundColor = Color.White,
            watermarkColor = colors.textPrimary.copy(alpha = opacity.selected + opacity.hover / 2f),
            watermarkTextStyle = typography.body.copy(fontSize = 14.sp),
            watermarkRotate = -22f,
            watermarkGapX = 100.dp,
            watermarkGapY = 100.dp,
            watermarkAlpha = opacity.selected + opacity.hover / 2f,
            codeBlockBackgroundColor = colors.surfaceElevated,
            codeBlockBorderColor = colors.border,
            codeBlockContentColor = colors.textPrimary,
            codeBlockKeywordColor = colors.primary,
            codeBlockStringColor = colors.success,
            codeBlockNumberColor = colors.warning,
            codeBlockCommentColor = colors.textSecondary,
            codeBlockFunctionColor = colors.info,
            codeBlockTypeColor = colors.info,
            codeBlockAnnotationColor = colors.error,
            codeBlockOperatorColor = colors.textSecondary,
            codeBlockPunctuationColor = colors.textSecondary,
            codeBlockLineNumberColor = colors.textSecondary,
            codeBlockHighlightedLineColor = colors.bgSelected,
            codeBlockHeaderBackgroundColor = colors.surface,
            codeBlockTextStyle = typography.body.copy(fontSize = 13.sp, lineHeight = 20.sp),
            codeBlockCornerRadius = control.medium.cornerRadius,
            codeBlockBorderWidth = control.borderWidth,
            codeBlockPadding = spacing.medium,
            markdownBlockSpacing = spacing.medium,
            markdownEditorMinHeight = 220.dp,
            mermaidNodeContainerColor = colors.surface,
            mermaidNodeBorderColor = colors.primary,
            mermaidNodeContentColor = colors.textPrimary,
            mermaidEdgeColor = colors.textSecondary,
            mermaidNodeCornerRadius = control.medium.cornerRadius,
            mermaidEntityHeaderColor = colors.bgHover,
            mermaidPrimaryKeyColor = colors.primary,
            mermaidForeignKeyColor = colors.info,
            // Note 暖色调由 warning 语义 token 派生（与 mermaid.live 的 note yellow 视觉对齐），
            // 填充用低透明度、描边用较高透明度，确保明/暗主题下均与参与方方框区分。
            mermaidNoteColor = colors.warning.copy(alpha = 0.20f),
            mermaidNoteBorderColor = colors.warning.copy(alpha = 0.75f),
        )
    }
}

@Immutable
data class PaletteLayoutTokens(
    val spaceSmallSpacing: Dp,
    val spaceMediumSpacing: Dp,
    val spaceLargeSpacing: Dp,
    val gridDefaultGutter: Dp,
    val affixDefaultOffset: Dp,
) {
    companion object {
        fun default(spacing: PaletteSpacing): PaletteLayoutTokens = PaletteLayoutTokens(
            spaceSmallSpacing = spacing.small,
            spaceMediumSpacing = spacing.small + spacing.extraSmall,
            spaceLargeSpacing = spacing.medium,
            gridDefaultGutter = spacing.none,
            affixDefaultOffset = spacing.none,
        )
    }
}

@Immutable
data class PaletteFloatingActionTokens(
    val backtopContainerColor: Color,
    val backtopIconColor: Color,
    val backtopSize: Dp,
    val backtopIconSize: Dp,
    val backtopCornerRadius: Dp,
    val backtopElevation: Dp,
    val backtopAnimationDurationMillis: Int,
    val floatButtonContainerColor: Color,
    val floatButtonIconColor: Color,
    val floatButtonTextColor: Color,
    val floatButtonSize: Dp,
    val floatButtonIconSize: Dp,
    val floatButtonCornerRadius: Dp,
    val floatButtonElevation: Dp,
    val floatButtonTextPadding: Dp,
    val floatButtonTextStyle: TextStyle,
) {
    companion object {
        fun default(
            colors: PaletteColors,
            spacing: PaletteSpacing,
            typography: PaletteTypography,
            elevation: PaletteElevation,
            motion: PaletteMotion,
        ): PaletteFloatingActionTokens = PaletteFloatingActionTokens(
            backtopContainerColor = colors.surface,
            backtopIconColor = colors.textPrimary,
            backtopSize = 40.dp,
            backtopIconSize = 20.dp,
            backtopCornerRadius = 50.dp,
            backtopElevation = elevation.raised,
            backtopAnimationDurationMillis = motion.durationNormal,
            floatButtonContainerColor = colors.surface,
            floatButtonIconColor = colors.textPrimary,
            floatButtonTextColor = colors.textPrimary,
            floatButtonSize = 48.dp,
            floatButtonIconSize = 20.dp,
            floatButtonCornerRadius = 12.dp,
            floatButtonElevation = 6.dp,
            floatButtonTextPadding = spacing.small + spacing.extraSmall,
            floatButtonTextStyle = typography.body.copy(fontSize = 14.sp),
        )
    }
}

@Immutable
data class PaletteScreenTokens(
    val backgroundColor: Color,
    val contentColor: Color,
    val successBackgroundColor: Color,
    val warningBackgroundColor: Color,
    val errorBackgroundColor: Color,
) {
    companion object {
        fun default(colors: PaletteColors): PaletteScreenTokens = PaletteScreenTokens(
            backgroundColor = colors.pageBackground,
            contentColor = colors.textPrimary,
            successBackgroundColor = colors.success,
            warningBackgroundColor = colors.warning,
            errorBackgroundColor = colors.error,
        )
    }
}
