package xyz.junerver.compose.palette.core.tokens

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class PaletteSemanticColors(
    val primary: Color,
    val onPrimary: Color,
    val border: Color,
    val surface: Color,
    val onSurface: Color,
    val hint: Color,
    val error: Color,
    val success: Color,
    val warning: Color,
    val info: Color,
    val danger: Color,
    val surfaceElevated: Color,
    val pageBackground: Color,
    val textSecondary: Color,
    val divider: Color,
    val overlay: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
) {
    fun toMaterialScheme(): ColorScheme = ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primary,
        onPrimaryContainer = onPrimary,
        inversePrimary = primary,
        secondary = info,
        onSecondary = onPrimary,
        secondaryContainer = info,
        onSecondaryContainer = onPrimary,
        tertiary = success,
        onTertiary = onPrimary,
        tertiaryContainer = success,
        onTertiaryContainer = onPrimary,
        background = pageBackground,
        onBackground = onSurface,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceElevated,
        onSurfaceVariant = textSecondary,
        surfaceTint = primary,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onPrimary,
        errorContainer = danger,
        onErrorContainer = onPrimary,
        outline = border,
        outlineVariant = divider,
        scrim = overlay,
        surfaceBright = surface,
        surfaceDim = pageBackground,
        surfaceContainerLowest = surface,
        surfaceContainerLow = surface,
        surfaceContainer = surfaceElevated,
        surfaceContainerHigh = surfaceElevated,
        surfaceContainerHighest = surfaceElevated,
        primaryFixed = primary,
        primaryFixedDim = primary,
        onPrimaryFixed = onPrimary,
        onPrimaryFixedVariant = onPrimary,
        secondaryFixed = info,
        secondaryFixedDim = info,
        onSecondaryFixed = onPrimary,
        onSecondaryFixedVariant = onPrimary,
        tertiaryFixed = success,
        tertiaryFixedDim = success,
        onTertiaryFixed = onPrimary,
        onTertiaryFixedVariant = onPrimary,
    )
}

fun PaletteColors.toSemanticColors(): PaletteSemanticColors = PaletteSemanticColors(
    primary = primary,
    onPrimary = onPrimary,
    border = border,
    surface = surface,
    onSurface = onSurface,
    hint = hint,
    error = error,
    success = success,
    warning = warning,
    info = info,
    danger = danger,
    surfaceElevated = surfaceElevated,
    pageBackground = pageBackground,
    textSecondary = textSecondary,
    divider = divider,
    overlay = overlay,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
)
