package xyz.junerver.compose.palette.code.lexer

internal val KotlinKeywords =
    setOf(
        "abstract",
        "as",
        "actual",
        "annotation",
        "break",
        "by",
        "catch",
        "class",
        "companion",
        "const",
        "continue",
        "context",
        "crossinline",
        "data",
        "delegate",
        "do",
        "dynamic",
        "else",
        "enum",
        "expect",
        "external",
        "false",
        "final",
        "finally",
        "for",
        "fun",
        "get",
        "if",
        "import",
        "in",
        "infix",
        "init",
        "inline",
        "inner",
        "interface",
        "internal",
        "is",
        "lateinit",
        "noinline",
        "null",
        "object",
        "open",
        "operator",
        "out",
        "override",
        "package",
        "private",
        "protected",
        "public",
        "reified",
        "return",
        "sealed",
        "set",
        "super",
        "suspend",
        "tailrec",
        "this",
        "throw",
        "try",
        "true",
        "typealias",
        "val",
        "value",
        "var",
        "vararg",
        "when",
        "where",
        "while",
        "constructor",
    )

internal val KotlinBuiltins =
    setOf(
        "println", "print", "readLine", "readln",
        "listOf", "mutableListOf", "arrayListOf",
        "mapOf", "mutableMapOf", "hashMapOf",
        "setOf", "mutableSetOf", "hashSetOf",
        "arrayOf", "intArrayOf", "longArrayOf", "floatArrayOf", "doubleArrayOf", "booleanArrayOf",
        "emptyList", "emptyMap", "emptySet",
        "listOfNotNull", "setOfNotNull",
        "buildList", "buildMap", "buildSet",
        "sequence", "generateSequence",
        "lazy", "lazyOf",
        "error", "require", "check",
        "TODO",
        "Pair", "Triple",
        "Regex",
    )

internal val KotlinPrimitiveTypes =
    setOf("Boolean", "Byte", "Char", "Double", "Float", "Int", "Long", "Short", "String", "Unit")

internal val JavaKeywords =
    setOf(
        "abstract",
        "assert",
        "boolean",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "class",
        "const",
        "continue",
        "default",
        "do",
        "double",
        "else",
        "enum",
        "extends",
        "false",
        "final",
        "finally",
        "float",
        "for",
        "if",
        "implements",
        "import",
        "instanceof",
        "int",
        "interface",
        "long",
        "module",
        "native",
        "new",
        "null",
        "opens",
        "open",
        "package",
        "permits",
        "private",
        "protected",
        "public",
        "record",
        "requires",
        "return",
        "sealed",
        "short",
        "static",
        "strictfp",
        "super",
        "switch",
        "synchronized",
        "this",
        "throw",
        "throws",
        "to",
        "transient",
        "true",
        "try",
        "uses",
        "var",
        "void",
        "volatile",
        "with",
        "while",
        "yield",
    )

internal val JavaPrimitiveTypes =
    setOf("boolean", "byte", "char", "double", "float", "int", "long", "short", "String", "void")

internal val JavaScriptKeywords =
    setOf(
        "async",
        "await",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "default",
        "else",
        "export",
        "false",
        "for",
        "from",
        "function",
        "if",
        "import",
        "let",
        "new",
        "null",
        "return",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "undefined",
        "var",
        "while",
    )

internal val JavaScriptPrimitiveTypes =
    setOf("Array", "Boolean", "Date", "Map", "Number", "Object", "Promise", "Set", "String")

internal val TypeScriptKeywords =
    JavaScriptKeywords +
        setOf(
            "as",
            "declare",
            "enum",
            "implements",
            "interface",
            "namespace",
            "private",
            "protected",
            "public",
            "readonly",
            "type",
        )

internal val TypeScriptPrimitiveTypes =
    JavaScriptPrimitiveTypes + setOf("any", "boolean", "never", "number", "string", "unknown", "void")

internal val PythonKeywords =
    setOf(
        "False",
        "None",
        "True",
        "and",
        "as",
        "assert",
        "async",
        "await",
        "break",
        "class",
        "continue",
        "def",
        "del",
        "elif",
        "else",
        "except",
        "finally",
        "for",
        "from",
        "global",
        "if",
        "import",
        "in",
        "is",
        "lambda",
        "nonlocal",
        "not",
        "or",
        "pass",
        "raise",
        "return",
        "try",
        "while",
        "with",
        "yield",
    )

internal val PythonPrimitiveTypes =
    setOf("bool", "bytes", "dict", "float", "frozenset", "int", "list", "set", "str", "tuple")

internal val ShellKeywords =
    setOf(
        "case",
        "do",
        "done",
        "elif",
        "else",
        "esac",
        "export",
        "fi",
        "for",
        "function",
        "if",
        "in",
        "local",
        "then",
        "while",
    )

internal val ShellBuiltins =
    setOf(
        "alias", "bg", "bind", "break", "builtin", "caller", "cd", "command",
        "compgen", "complete", "compopt", "continue", "declare", "dirs", "disown",
        "echo", "enable", "eval", "exec", "exit", "fc", "fg", "getopts", "hash",
        "help", "history", "jobs", "kill", "let", "logout", "mapfile", "popd",
        "printf", "pushd", "pwd", "read", "readarray", "readonly", "return",
        "set", "shift", "shopt", "source", "suspend", "test", "times", "trap",
        "true", "type", "typeset", "ulimit", "umask", "unalias", "unset", "wait",
    )

internal val SqlKeywords =
    setOf(
        "ADD",
        "ALL",
        "ALTER",
        "AND",
        "ANY",
        "AS",
        "ASC",
        "BETWEEN",
        "BY",
        "CASE",
        "CHECK",
        "CONSTRAINT",
        "CROSS",
        "CURRENT",
        "CREATE",
        "DEFAULT",
        "DELETE",
        "DESC",
        "DISTINCT",
        "DROP",
        "ELSE",
        "END",
        "EXCEPT",
        "EXISTS",
        "FALSE",
        "FETCH",
        "FIRST",
        "FOLLOWING",
        "FOR",
        "FOREIGN",
        "FROM",
        "FULL",
        "GRANT",
        "GROUP",
        "HAVING",
        "IF",
        "IN",
        "INDEX",
        "INNER",
        "INSERT",
        "INTERSECT",
        "INTO",
        "IS",
        "JOIN",
        "KEY",
        "LAST",
        "LEFT",
        "LIKE",
        "LIMIT",
        "NEXT",
        "NO",
        "NOT",
        "NULL",
        "OFFSET",
        "ONLY",
        "OVER",
        "ON",
        "OR",
        "ORDER",
        "OUTER",
        "PARTITION",
        "PRECEDING",
        "PRIMARY",
        "RANGE",
        "REFERENCES",
        "REPLACE",
        "RIGHT",
        "ROWS",
        "SELECT",
        "SET",
        "TABLE",
        "THEN",
        "TO",
        "TRUE",
        "UNBOUNDED",
        "UNION",
        "UNIQUE",
        "UPDATE",
        "USING",
        "VALUES",
        "VIEW",
        "WHEN",
        "WHERE",
        "WITH",
    )

internal val SqlTypes =
    setOf(
        "BIGINT",
        "BINARY",
        "BLOB",
        "BOOLEAN",
        "CHAR",
        "CHARACTER",
        "CLOB",
        "DATE",
        "DECIMAL",
        "DOUBLE",
        "FLOAT",
        "INTEGER",
        "INT",
        "JSON",
        "JSONB",
        "NCHAR",
        "NCLOB",
        "NUMERIC",
        "NVARCHAR",
        "REAL",
        "SERIAL",
        "SMALLINT",
        "TEXT",
        "TIME",
        "TIMESTAMP",
        "TINYINT",
        "UUID",
        "VARBINARY",
        "VARCHAR",
    )

internal val SqlOperators = setOf('+', '-', '*', '/', '%', '=', '!', '<', '>', '|')

internal val SqlPunctuation = setOf('(', ')', ',', '.', ';')

internal val CssValueKeywords =
    setOf(
        "absolute",
        "auto",
        "block",
        "flex",
        "grid",
        "hidden",
        "inline",
        "none",
        "relative",
        "solid",
    )

internal val HtmlAttributes: Set<String> = emptySet()

internal val HtmlEventAttributes: Set<String> = emptySet()

internal val DockerfileInstructions =
    setOf(
        "ADD",
        "ARG",
        "CMD",
        "COPY",
        "ENTRYPOINT",
        "ENV",
        "EXPOSE",
        "FROM",
        "HEALTHCHECK",
        "LABEL",
        "MAINTAINER",
        "ONBUILD",
        "RUN",
        "SHELL",
        "STOPSIGNAL",
        "USER",
        "VOLUME",
        "WORKDIR",
    )

internal val DockerfileSecondaryKeywords = setOf("AS")

internal val GraphQlKeywords =
    setOf(
        "directive",
        "enum",
        "extend",
        "fragment",
        "implements",
        "input",
        "interface",
        "mutation",
        "on",
        "query",
        "repeatable",
        "scalar",
        "schema",
        "subscription",
        "type",
        "union",
        "true",
        "false",
        "null",
    )

internal val YamlKeywords = setOf("true", "false", "null", "yes", "no", "on", "off")

internal val TomlKeywords = setOf("true", "false")

internal val IniKeywords = setOf("true", "false", "yes", "no", "on", "off", "null")
